
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: httpendpoints.dapr.io
  labels:
    app.kubernetes.io/part-of: "dapr"
spec:
  group: dapr.io
  names:
    kind: HTTPEndpoint
    listKind: HTTPEndpointList
    plural: httpendpoints
    singular: httpendpoint
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HTTPEndpoint describes a Dapr HTTPEndpoint type for external
          service invocation. This endpoint can be external to Dapr, or external to
          the environment.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          auth:
            description: Auth represents authentication details for the component.
            properties:
              secretStore:
                type: string
            required:
            - secretStore
            type: object
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          scopes:
            items:
              type: string
            type: array
          spec:
            description: HTTPEndpointSpec describes an access specification for allowing
              external service invocations.
            properties:
              baseUrl:
                type: string
              clientTLS:
                description: TLS describes how to build client or server TLS configurations.
                properties:
                  certificate:
                    description: TLSDocument describes and in-line or pointer to a
                      document to build a TLS configuration.
                    properties:
                      secretKeyRef:
                        description: SecretKeyRef is the reference of a value in a
                          secret store component.
                        properties:
                          key:
                            description: Field in the secret.
                            type: string
                          name:
                            description: Secret name.
                            type: string
                        required:
                        - name
                        type: object
                      value:
                        description: Value of the property, in plaintext.
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  privateKey:
                    description: TLSDocument describes and in-line or pointer to a
                      document to build a TLS configuration.
                    properties:
                      secretKeyRef:
                        description: SecretKeyRef is the reference of a value in a
                          secret store component.
                        properties:
                          key:
                            description: Field in the secret.
                            type: string
                          name:
                            description: Secret name.
                            type: string
                        required:
                        - name
                        type: object
                      value:
                        description: Value of the property, in plaintext.
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  renegotiation:
                    default: Never
                    description: Renegotiation sets the underlying tls negotiation
                      strategy for an http channel.
                    enum:
                    - Never
                    - OnceAsClient
                    - FreelyAsClient
                    type: string
                  rootCA:
                    description: TLSDocument describes and in-line or pointer to a
                      document to build a TLS configuration.
                    properties:
                      secretKeyRef:
                        description: SecretKeyRef is the reference of a value in a
                          secret store component.
                        properties:
                          key:
                            description: Field in the secret.
                            type: string
                          name:
                            description: Secret name.
                            type: string
                        required:
                        - name
                        type: object
                      value:
                        description: Value of the property, in plaintext.
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                type: object
              headers:
                items:
                  description: NameValuePair is a name/value pair.
                  properties:
                    envRef:
                      description: EnvRef is the name of an environmental variable
                        to read the value from.
                      type: string
                    name:
                      description: Name of the property.
                      type: string
                    secretKeyRef:
                      description: SecretKeyRef is the reference of a value in a secret
                        store component.
                      properties:
                        key:
                          description: Field in the secret.
                          type: string
                        name:
                          description: Secret name.
                          type: string
                      required:
                      - name
                      type: object
                    value:
                      description: Value of the property, in plaintext.
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                  - name
                  type: object
                type: array
            required:
            - baseUrl
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []