
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-placement
  namespace: {{ .Release.Namespace }}
  labels:
    app: actions-placement
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: actions-placement
  template:
    metadata:
      labels:
        app: actions-placement
    spec:
      containers:
      - name: actions-placement
{{- if contains "/" .Values.image.name }}
        image: "{{ .Values.image.name }}"
{{- else }}
        image: "{{ $.Values.global.registry }}/actions:{{ $.Values.global.tag }}"
{{- end }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        ports:
          - containerPort: 50005
        command:
        - "./placement"
        args:
        - "--log-level"
        - {{ .Values.logLevel }}
      serviceAccountName: actions-operator