---
# Source: actions-operator/charts/actions_controller/templates/actions_controller_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-controller
  namespace: default
  labels:
    app: actions-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-controller
  template:
    metadata:
      labels:
        app: actions-controller
    spec:
      containers:
      - name: actions-controller
        repository: 
        image: "actionscore.azurecr.io/actions:latest"
        env:
        - name: RUNTIME_IMAGE
          value: "actionscore.azurecr.io/actions:latest"
        - name: NAMESPACE
          value: default
        imagePullPolicy: 
        ports:
        - containerPort: 6500
        command: ["./controller"]
      serviceAccountName: actions-controller            
