parameters:
  pool: 'macOS'
  targetOS: 'darwin'
  binaryName: 'action'
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(system.defaultWorkingDirectory)/gopath/src/github.com/$(build.repository.name)'

jobs:
- job: build_${{ parameters.binaryName }}_${{ parameters.targetOS }}
  pool:
    vmImage: '${{ parameters.pool }}-latest'
  steps:
    - task: GoTool@0
      inputs:
        version: '1.12'
    - script: |
        mkdir -p '${{ parameters.GOPATH }}/pkg'
        mkdir -p '${{ parameters.modulePath }}'
        shopt -s extglob
        mv '${{ parameters.GOPATH }}' '${{ parameters.modulePath }}'
      displayName: 'Set up the Go workspace'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-v -t -d ./...'
        workingDirectory: '${{ parameters.modulePath }}/cmd/${{ parameters.binaryName }}'
        displayName: 'Run go get'
    - task: Go@0
      inputs:
        command: 'build'
        arguments: '-v -o $(Build.BinariesDirectory)/${{ parameters.targetOS }}/${{ parameters.binaryName }}'
        workingDirectory: '${{ parameters.modulePath }}/cmd/${{ parameters.binaryName }}'
        displayName: 'Run go build'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)/${{ parameters.targetOS }}'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}/${{ parameters.binaryName }}_${{ parameters.targetOS }}.zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        displayName: 'Publish build artifacts'
