parameters:
  poolImage: 'macOS-latest'
  targetOS: 'darwin'
  targetArch: 'amd64'
  binaryName: 'actionsrt'

jobs:
- job: build_${{ parameters.targetOS }}_${{ parameters.targetArch }}_${{ parameters.binaryName }}
  variables:
    GOOS: ${{ parameters.targetOS }}
    GOARCH: ${{ parameters.targetArch }}
  pool:
    vmImage: '${{ parameters.poolImage }}'
  steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '1.12'
    - task: Bash@3
      displayName: 'Set up the Go workspace'
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p '$(GOPATH)/pkg'
          mkdir -p '$(GOPATH)/bin'
          mkdir -p '$(modulePath)'
          shopt -s extglob
          mv !(gopath) '$(modulePath)'
          echo '##vso[task.prependpath]$(GOBIN)'
    - task: CmdLine@2
      displayName: 'Run make test'
      condition: ne('${{ parameters.targetArch }}', 'arm')
      inputs:
        script: 'make test'
        workingDirectory: '$(modulePath)'
        failOnStderr: true
    - task: CmdLine@2
      displayName: 'Run make build'
      inputs:
        script: 'make build BINARIES=${{ parameters.binaryName }} TARGETS=${{ parameters.targetOS }} ARCH=$(GOARCH)'
        workingDirectory: '$(modulePath)'
        failOnStderr: true
    - task: ArchiveFiles@2
      displayName: 'Build $(GOARCH)/${{ parameters.binaryName }}_${{ parameters.targetOS }}.zip'
      inputs:
        rootFolderOrFile: '$(modulePath)/dist/${{ parameters.targetOS }}_$(GOARCH)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)/${{ parameters.binaryName }}_${{ parameters.targetOS }}_$(GOARCH).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
