parameters:
  poolImage: 'macOS-latest'
  targetOS: 'darwin'
  targetArch: 'amd64'
  binaryExtension: ''
  dependStep: 'release_environment'
  relVersion: ''
jobs:
- job: build_${{ parameters.targetOS }}_${{ parameters.targetArch }}
  dependsOn:
    ${{ parameters.dependStep }}
  variables:
    GOOS: ${{ parameters.targetOS }}
    GOARCH: ${{ parameters.targetArch }}
    REL_VERSION: ${{ parameters.relVersion }}
    GOPROXY: https://proxy.golang.org
  pool:
    vmImage: '${{ parameters.poolImage }}'
  steps:
    - task: GoTool@0
      displayName: 'Install Go'
      inputs:
        version: '1.12'
    - task: Bash@3
      displayName: 'Set up the Go workspace'
      inputs:
        targetType: 'inline'
        script: |
          mkdir -p '$(GOPATH)/pkg'
          mkdir -p '$(GOPATH)/bin'
          mkdir -p '$(modulePath)'
          shopt -s extglob
          mv !(gopath) '$(modulePath)'
          echo '##vso[task.prependpath]$(GOBIN)'
    - task: CmdLine@2
      displayName: 'Run make test'
      condition: ne('${{ parameters.targetArch }}', 'arm')
      inputs:
        script: 'make test'
        workingDirectory: '$(modulePath)'
        failOnStderr: false
    - task: CmdLine@2
      displayName: 'Run make build'
      inputs:
        script: 'make build TARGETS=${{ parameters.targetOS }} ARCH=$(GOARCH)'
        workingDirectory: '$(modulePath)'
        failOnStderr: false
    # Zip binaries separately
    - task: ArchiveFiles@2
      displayName: 'Build $(GOARCH)/actionsrt_${{ parameters.targetOS }}.zip'
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        rootFolderOrFile: '$(modulePath)/dist/${{ parameters.targetOS }}_$(GOARCH)/actionsrt${{ parameters.binaryExtension }}'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)/actionsrt_${{ parameters.targetOS }}_$(GOARCH).zip'
        replaceExistingArchive: true
    - task: ArchiveFiles@2
      displayName: 'Build $(GOARCH)/injector_${{ parameters.targetOS }}.zip'
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        rootFolderOrFile: '$(modulePath)/dist/${{ parameters.targetOS }}_$(GOARCH)/injector${{ parameters.binaryExtension }}'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)/injector_${{ parameters.targetOS }}_$(GOARCH).zip'
        replaceExistingArchive: true
    - task: ArchiveFiles@2
      displayName: 'Build $(GOARCH)/operator_${{ parameters.targetOS }}.zip'
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        rootFolderOrFile: '$(modulePath)/dist/${{ parameters.targetOS }}_$(GOARCH)/operator${{ parameters.binaryExtension }}'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)/operator_${{ parameters.targetOS }}_$(GOARCH).zip'
        replaceExistingArchive: true
    - task: ArchiveFiles@2
      displayName: 'Build $(GOARCH)/placement_${{ parameters.targetOS }}.zip'
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        rootFolderOrFile: '$(modulePath)/dist/${{ parameters.targetOS }}_$(GOARCH)/placement${{ parameters.binaryExtension }}'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)/placement_${{ parameters.targetOS }}_$(GOARCH).zip'
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      condition: ne(variables['Build.Reason'], 'PullRequest')
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/${{ parameters.targetOS }}_$(GOARCH)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
