parameters:
  pool: 'macOS'
  binaryName: ''
  GOPATH: '$(system.defaultWorkingDirectory)/gopath'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

jobs:
- job: build_${{ parameters.binaryName }}_${{ parameters.pool }}
  pool:
    vmImage: '${{ parameters.pool }}-latest'
  steps:
    - task: GoTool@0
      inputs:
        version: '1.12'
    - script: |
        mkdir -p '${{ parameters.GOPATH }}/pkg'
        mkdir -p '${{ parameters.modulePath }}'
        shopt -s extglob
        mv !(gopath) '${{ parameters.modulePath }}'
      displayName: 'Set up the Go workspace'
    - task: Go@0
      inputs:
        command: 'get'
        arguments: '-v -t -d ./...'
        workingDirectory: '${{ parameters.modulePath }}/cmd/${{ parameters.binaryName }}'
        displayName: 'Run go get'
    - task: Go@0
      inputs:
        command: 'build'
        arguments: '-v -o $(Build.ArtifactStagingDirectory)/${{ parameters.binaryName }}'
        workingDirectory: '${{ parameters.modulePath }}/cmd/${{ parameters.binaryName }}'
        displayName: 'Run go build'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
        displayName: 'Publish build artifacts'
