---
# Source: actions-operator/charts/actions_sidecar_injector/templates/actions_sidecar_injector_webhook_config.yaml

apiVersion: v1
kind: Secret
metadata:
  name: actions-sidecar-injector-cert
  labels:
    app: actions-sidecar-injector
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR6RENDQXJTZ0F3SUJBZ0lRT202SjJoSUg0MUFVcDhlZXY2Y2xhREFOQmdrcWhraUc5dzBCQVFzRkFEQW0KTVNRd0lnWURWUVFERXh0aFkzUnBiMjV6TFhOcFpHVmpZWEl0YVc1cVpXTjBiM0l0WTJFd0hoY05NVGt3T0RJegpNakl4TmpRMFdoY05Namt3T0RJd01qSXhOalEwV2pBak1TRXdId1lEVlFRREV4aGhZM1JwYjI1ekxYTnBaR1ZqCllYSXRhVzVxWldOMGIzSXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEbC9NSisKUDlSQU9ZRVVBWW5iVUtidU5YcWdmTFhnZ0V2NEI0V2xVMHBFaEg0VFVaYys2T1NaYW5kek9aRkVPcnBncTZmVAo2bUpnWHUrdTdJY05Ec0xSRlAveVh2NHZrc3RtR05rTjNZZ3ZyeWF0K2xld0dBem95VDlpQjBRbUtpUWNwM0ZiCmVkZlZUQVRTb1o4czR5ZktJanNNV2ROU2ZrdkR1WkZwTStKdHZjM0VaclVnZytsRFE1eUlXbW96b1c2OE5tencKVERTU2RKWkxHaFlmbXU3L3dsUjNEdXpjMVhtbU5QclpmcHR1ckhLTGZCd0xLZEdnZTErMDVET0xDTEdWeDBOSApobUJZS2FPclkwbHhqSVJuQkt5dUh1NXlPSjBQL3l5ZkdmWHh5dWMvVWZZYUp3azJLUk9jUVUxRXV1RkRkeG40Ck1NUDU5YTNGVjNPK3JnWmpBZ01CQUFHamdmZ3dnZlV3RGdZRFZSMFBBUUgvQkFRREFnV2dNQjBHQTFVZEpRUVcKTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQU1CZ05WSFJNQkFmOEVBakFBTUlHMUJnTlZIUkVFZ2EwdwpnYXFDSUdGamRHbHZibk10YzJsa1pXTmhjaTFwYm1wbFkzUnZjaTVrWldaaGRXeDBnaVJoWTNScGIyNXpMWE5wClpHVmpZWEl0YVc1cVpXTjBiM0l1WkdWbVlYVnNkQzV6ZG1PQ0xHRmpkR2x2Ym5NdGMybGtaV05oY2kxcGJtcGwKWTNSdmNpNWtaV1poZFd4MExuTjJZeTVqYkhWemRHVnlnakpoWTNScGIyNXpMWE5wWkdWallYSXRhVzVxWldOMApiM0l1WkdWbVlYVnNkQzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCmd6bzdZSGduNmhDTWpyeHBsK0RHY3oyWmJ2c28vcmdSRi9VNkNBVm1aVTRnOFg5Zmgxbk1zQUtlcDdPbU1kbFAKQVNKQWhaSE5sK21DRjhPRUw0dDNIUjRCNVF1Ym1KUXdLc1B0SjlJOFVjZkwzNXlkQUdYb2hXQmlQKzh4VlFGVgpwbGNNWXZqcUhJaGFJV0NlS21IRmFWVVFWR0Z1cEdxaUtVV3F2bmwvcGVvb040VHNJeEhJcEJLbnZRN2theGRPCllJVEtHVnJCSE01dEtWbWdLUTFXbE4rRitmbWZ5Y2lEc3R1RmpMSWpYRUlodWhXeEkyTEl1dmtaTW5INXdKR0sKcGtNTEdPMStVWXFrZTlwR0xUMVB3KzBkR3RqTUp4SnBsN20rdDV3YzRCYXlPT2JrUUxGUzlHeklkM2llWnZNVQpZVVJ1a1hoZ2x4US85d0tQSEhqZ2J3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBNWZ6Q2ZqL1VRRG1CRkFHSjIxQ203alY2b0h5MTRJQkwrQWVGcFZOS1JJUitFMUdYClB1amttV3AzY3ptUlJEcTZZS3VuMCtwaVlGN3ZydXlIRFE3QzBSVC84bDcrTDVMTFpoalpEZDJJTDY4bXJmcFgKc0JnTTZNay9ZZ2RFSmlva0hLZHhXM25YMVV3RTBxR2ZMT01ueWlJN0RGblRVbjVMdzdtUmFUUGliYjNOeEdhMQpJSVBwUTBPY2lGcHFNNkZ1dkRaczhFdzBrblNXU3hvV0g1cnUvOEpVZHc3czNOVjVwalQ2Mlg2YmJxeHlpM3djCkN5blJvSHRmdE9Reml3aXhsY2REUjRaZ1dDbWpxMk5KY1l5RVp3U3NyaDd1Y2ppZEQvOHNueG4xOGNyblAxSDIKR2ljSk5pa1RuRUZOUkxyaFEzY1orREREK2ZXdHhWZHp2cTRHWXdJREFRQUJBb0lCQVFEQkVCQ1krSzROaC9oQwpPaFJtcGVxcjF2cnMxQ085cFJXZ3pYZTBWQm5wTUt2QlBlSFFMcU1QNGw4SnZBNmxEd083K1AwMm1QQWlaQytpClVPNEIyUjFUZE9SeXFxbUllQnNFeHVFV2tad3NJMFUrRVFRaFQ5OHVYeG8xQ1ZKOUV5MGpYTEI5RU9oTkpyWjUKdHJFdmRqVEZxenlVWHFkVi9hMU9UVzJ5dVpwZmNia2lwMlB3S2xtT2hzak44N1QzdGxhQTVYaHJRcWFiajliNQpkNXEwTllaQnVlVmY3Y05lT1ROR3hXbWQra0szby9Ba1hxRTkwSGpHTVNNeFc2V3hTZ25HWjBWOXQ1Q3VEb0FJCkhiNlZOL05ESVNrTlBLSjdnM2FWenZRZHBLVklwN3N5azFGcFJuVzFyRDFkV0JrMklKQXYvbTRMUXhvdUhmN3QKR2dGSHo1NVJBb0dCQU9sTjYyMHJ5VWc1d0JCYVNIcWkzRlpjTXp0bjRDRjlFelM2WmtnS3h0WkVhR21OT2FtbwpCZ1VUemNTcjhDTy9naWFpanhVUGYrQWVKTzhUS1RzcHVSMFlhSkpCNHhSTDdCb3kxVnFoYVZxN1g5V0U1SEYzCkNYTkNQOExCRDJ6V3MwaHNQQnBlVlM3M2tKZ3UwSnV6WGkxc3M1Ukl3alllRVdNNDhidVR0OEc3QW9HQkFQeGMKUEJGMnFUN21iNVZmRktUMlZMVlIxWVVtSExDMUpnZmVCTDBYMW81WG5MbG9jK1ZmZnpQZmRCMEZRVXRhV2YrTwp0c0RXWnRoV0l2ZmhyNHZVS3o4NGxiNnhndE1jWlUyeEtzOW5VZC94aitQOUFDTXVlM0dwdVdSK3BBcjMwelEzCmNMQzY0QzlISW5jdmhyWFpDRzRoVi9Zb0NoamVzbVlJN2J1ZkZJOTVBb0dBTlVtMzRVcWtBZHcyODBVNzBzOEsKRnF1ZWhBNFkwbTFZQ3E0Y21JM2xscUV2WEJTR3ZDcUZuWGxGZ1l0b0lUSW56eDFJSXg1VUxlT1V1Z3FkVzBjUApZZ2JtTTZuYTdSTGVUYW1ZczhlMFlhWDBvTGRtMmtlL0g5VmM3T1hkMlJVOUEraTgzYVQ0UGU4TDFzYXluUzJkCjhEQW80RkN5RTF4UXltSUNUTDdUdE9zQ2dZQk1iSVpJWjU0VGpXZUhYZGI3cWhtM0c0UkZJV2lZM3hNWVdOVW8KaXJxUU90b2NrQlJoQjAyWFlQbGgvSUJzbUgwZTFwSmp6Y294Zzh4dE15eWRkUEJ2NGV2L1p2U09pRS9wZWxqVApuSjkvNlVEQk01SkNGVWFQQW01Qmo5U1ArY005VWZqUG5KaGQyUFlJRUIyRW5xaGQ2YjBncjdsM0ZLSUVJbm9VClVyWEFTUUtCZ0h1ZnRrTTkvY1pVYzhYenZudTVKSHdxWUtsN0wyVTh2a3dsc0lVanV0M0RzZkVrVDhlbXF2aHQKb1d3WEhCdE9GdkMwRGJWQlFpcUJ5NEZJcUNJd1hpaFNiVEpaSXpDQ2F3eWZ3emRoSUdoRGFKT3dDU1FVZ3E1MApnU0dOcFRrRVlLM2hrZ21BNGY2UlJJSnlLUExLdHFoNldjQ2JCYlNQcU5aNU10UlRFVk4zCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: actions-sidecar-injector
  labels:
    app: actions-sidecar-injector
webhooks:
- name: sidecar-injector.actions.io
  clientConfig:
    service:
      namespace: actions-system
      name: actions-sidecar-injector
      path: "/mutate"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHRENDQWdDZ0F3SUJBZ0lRUHU0SU5ZcTA1T1ZyelJiejZqOHMxREFOQmdrcWhraUc5dzBCQVFzRkFEQW0KTVNRd0lnWURWUVFERXh0aFkzUnBiMjV6TFhOcFpHVmpZWEl0YVc1cVpXTjBiM0l0WTJFd0hoY05NVGt3T0RJegpNakl4TmpRMFdoY05Namt3T0RJd01qSXhOalEwV2pBbU1TUXdJZ1lEVlFRREV4dGhZM1JwYjI1ekxYTnBaR1ZqCllYSXRhVzVxWldOMGIzSXRZMkV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3MKajQzWWd0aWlxa3VZdTFheWxtQ1B4M0gzcU5vOSt5N3hOZms0Q1VwQkFpa25lcGxSR2daUVBWYTUwV0tFbGhrQgpjNHFuSWhOSk8xbmp5WCtCUXh4bW5DWll1TEV2a2ZLb1BELy95cVJTay9CRVNIbjdjUlN1bkUvQ0Q2bHowTTV4CnNyUEdFT2JXMFEvREJxUUN5bWppNkFwOXJzbzIybEZHMjkrUXg0NTZQNEdQemNZTWQzekM2RVowdDVrTGZEVU4KUURITFUzcEtFaGtPU1RSc1crNjVEcUkwcmhEdk5DTHIrWGVCa0RrS2lZaUUrci9UN3B3NEpKa1lWT2xMaXpLeQp0R3QxOGhMaitpa3kwK3JoTFgzM0NOd0RwbTloaUVoMHRRWTNCYmY1eGJjRlNwUGhSc2U4TE9YU200MGVmSFpYCnkxME56OHFpOFB4ZUJrMEs0eXFaQWdNQkFBR2pRakJBTUE0R0ExVWREd0VCL3dRRUF3SUNwREFkQmdOVkhTVUUKRmpBVUJnZ3JCZ0VGQlFjREFRWUlLd1lCQlFVSEF3SXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRwo5dzBCQVFzRkFBT0NBUUVBTndPdU81QksrUUtFNFhETnJrV3h5TlNqMkR3MDdtZDNCZnR4NElWNkhLeHUvcGlCClR6V005ZXBXWFlTTGR2d0dvazY3SWxVNm9vaWljdVh2ZkZVUFdKeCs2WDFPZ0RGeEVYZXlXZmlId0I4b2Q2emcKUFFuYVNidVRqWGNhM3FuNmo2eGY5djdkRVFQcGxNeW5JTXdHdFdKaUJhTUIrcURyalRFSGVaRlgxWkVJRVFnRQphVG5UTXVkdVBIdGcrazZ1SUxaYU5EekxPQStzbjZ4UlJ0WXJHeEtOTGZkQStxS3VtU2VuZjV3TzhycEE3czlnClhKRHVUNTlQQWRJRFhZZTZKRk1kdUFXRnJzN1ZrSm1ueThhM0g4cVVlMGl1Q2dzRFdrL0dENTZjcGJNS09CbGwKM0NLTzhQSVc2MFloQm1ob2FKa1lHVUkzODh6RDArMHdoelJ4K3c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    resources:
    - pods
    operations:
    - CREATE
  failurePolicy: Ignore
---
# Source: actions-operator/charts/actions_rbac/templates/ServiceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-operator
  namespace: actions-system

---
# Source: actions-operator/charts/actions_crd/templates/components.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.actions.io
  namespace: actions-system
spec:
  group: actions.io
  version: v1alpha1
  names:
    kind: Component
    plural: components
    singular: component
    categories:
    - all
    - actions
  scope: Namespaced
---
# Source: actions-operator/charts/actions_rbac/templates/ClusterRoleBinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: actions-operator
subjects:
- kind: ServiceAccount
  name: actions-operator
  namespace: actions-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: actions-operator/charts/actions_operator/templates/actions_operator_service.yaml
kind: Service
apiVersion: v1
metadata:
  name: actions-api
  namespace: actions-system
spec:
  selector:
    app: actions-operator
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 6500  
---
# Source: actions-operator/charts/actions_placement/templates/actions_placement_service.yaml
kind: Service
apiVersion: v1
metadata:
  name: actions-placement
  namespace: actions-system
spec:
  selector:
    app: actions-placement
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 50005

---
# Source: actions-operator/charts/actions_sidecar_injector/templates/actions_sidecar_injector_service.yaml
apiVersion: v1
kind: Service
metadata:
  metadata:
  name: actions-sidecar-injector
  namespace: actions-system
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: actions-sidecar-injector
---
# Source: actions-operator/charts/actions_operator/templates/actions_operator_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-operator
  namespace: actions-system
  labels:
    app: actions-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-operator
  template:
    metadata:
      labels:
        app: actions-operator
    spec:
      containers:
      - name: actions-operator
        repository: 
        image: "actionscore.azurecr.io/actions:latest"
        env:
        - name: NAMESPACE
          value: actions-system
        imagePullPolicy: Always
        ports:
        - containerPort: 6500
        command: ["./operator"]
      serviceAccountName: actions-operator            

---
# Source: actions-operator/charts/actions_placement/templates/actions_placement_deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-placement
  namespace: actions-system
  labels:
    app: actions-placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-placement
  template:
    metadata:
      labels:
        app: actions-placement
    spec:
      containers:
      - name: actions-placement
        repository: 
        image: "actionscore.azurecr.io/actions:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 50005
        command: ["./placement"]
      serviceAccountName: actions-operator
---
# Source: actions-operator/charts/actions_sidecar_injector/templates/actions_sidecar_injector_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-sidecar-injector
  labels:
    app: actions-sidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-sidecar-injector
  template:
    metadata:
      labels:
         app: actions-sidecar-injector
    spec:
      serviceAccountName: actions-operator
      containers:
      - name: sidecar-injector
        image: "actionscore.azurecr.io/actions:latest"
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
        command: ["./injector"]
        env:
        - name: TLS_CERT_FILE
          value: /actions/cert/tls.crt
        - name: TLS_KEY_FILE
          value: /actions/cert/tls.key
        - name: SIDECAR_IMAGE
          value: "actionscore.azurecr.io/actions:latest"
        - name: NAMESPACE
          value: actions-system
        ports:
        - name: https
          containerPort: 4000
          protocol: TCP
        volumeMounts:
        - name: cert
          mountPath: /actions/cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          secretName: actions-sidecar-injector-cert
