// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sentry.proto

package sentry

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignCertificateRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A PEM-encoded x509 CSR.
	CertificateSigningRequest []byte   `protobuf:"bytes,2,opt,name=certificate_signing_request,json=certificateSigningRequest,proto3" json:"certificate_signing_request,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *SignCertificateRequest) Reset()         { *m = SignCertificateRequest{} }
func (m *SignCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*SignCertificateRequest) ProtoMessage()    {}
func (*SignCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_121fa6bf7f0f35e6, []int{0}
}

func (m *SignCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignCertificateRequest.Unmarshal(m, b)
}
func (m *SignCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignCertificateRequest.Marshal(b, m, deterministic)
}
func (m *SignCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignCertificateRequest.Merge(m, src)
}
func (m *SignCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_SignCertificateRequest.Size(m)
}
func (m *SignCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignCertificateRequest proto.InternalMessageInfo

func (m *SignCertificateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SignCertificateRequest) GetCertificateSigningRequest() []byte {
	if m != nil {
		return m.CertificateSigningRequest
	}
	return nil
}

type SignCertificateResponse struct {
	// A PEM-encoded x509 Certificate.
	WorkloadCertificate []byte `protobuf:"bytes,1,opt,name=workload_certificate,json=workloadCertificate,proto3" json:"workload_certificate,omitempty"`
	// A list of PEM-encoded x509 Certificates that establish the trust chain
	// between the workload certificate and the well-known trust root cert.
	TrustChainCertificates [][]byte             `protobuf:"bytes,2,rep,name=trust_chain_certificates,json=trustChainCertificates,proto3" json:"trust_chain_certificates,omitempty"`
	ValidUntil             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}             `json:"-"`
	XXX_unrecognized       []byte               `json:"-"`
	XXX_sizecache          int32                `json:"-"`
}

func (m *SignCertificateResponse) Reset()         { *m = SignCertificateResponse{} }
func (m *SignCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*SignCertificateResponse) ProtoMessage()    {}
func (*SignCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_121fa6bf7f0f35e6, []int{1}
}

func (m *SignCertificateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignCertificateResponse.Unmarshal(m, b)
}
func (m *SignCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignCertificateResponse.Marshal(b, m, deterministic)
}
func (m *SignCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignCertificateResponse.Merge(m, src)
}
func (m *SignCertificateResponse) XXX_Size() int {
	return xxx_messageInfo_SignCertificateResponse.Size(m)
}
func (m *SignCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignCertificateResponse proto.InternalMessageInfo

func (m *SignCertificateResponse) GetWorkloadCertificate() []byte {
	if m != nil {
		return m.WorkloadCertificate
	}
	return nil
}

func (m *SignCertificateResponse) GetTrustChainCertificates() [][]byte {
	if m != nil {
		return m.TrustChainCertificates
	}
	return nil
}

func (m *SignCertificateResponse) GetValidUntil() *timestamp.Timestamp {
	if m != nil {
		return m.ValidUntil
	}
	return nil
}

func init() {
	proto.RegisterType((*SignCertificateRequest)(nil), "sentry.SignCertificateRequest")
	proto.RegisterType((*SignCertificateResponse)(nil), "sentry.SignCertificateResponse")
}

func init() { proto.RegisterFile("sentry.proto", fileDescriptor_121fa6bf7f0f35e6) }

var fileDescriptor_121fa6bf7f0f35e6 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0xc6, 0x6d, 0x07, 0x03, 0xcf, 0x8a, 0x42, 0x94, 0x59, 0x2b, 0xb8, 0xd2, 0xab, 0x5e, 0x75,
	0x38, 0x6f, 0x04, 0x41, 0x90, 0xbe, 0x41, 0x36, 0x6f, 0xbc, 0x29, 0x5d, 0x9b, 0x75, 0x07, 0xbb,
	0xa4, 0x26, 0xa7, 0x8a, 0xcf, 0xe7, 0x8b, 0xc9, 0x9a, 0x15, 0x8b, 0x7f, 0x2e, 0x93, 0xef, 0x77,
	0xce, 0x47, 0x7e, 0x01, 0xcf, 0x08, 0x49, 0xfa, 0x23, 0x69, 0xb4, 0x22, 0xc5, 0xc6, 0xf6, 0x14,
	0xcc, 0x2a, 0xa5, 0xaa, 0x5a, 0xcc, 0xbb, 0xdb, 0x75, 0xbb, 0x99, 0x13, 0xee, 0x84, 0xa1, 0x7c,
	0xd7, 0x58, 0x30, 0xda, 0xc2, 0x74, 0x89, 0x95, 0x4c, 0x85, 0x26, 0xdc, 0x60, 0x91, 0x93, 0xe0,
	0xe2, 0xb5, 0x15, 0x86, 0xd8, 0x09, 0xb8, 0x58, 0xfa, 0x4e, 0xe8, 0xc4, 0xc7, 0xdc, 0xc5, 0x92,
	0x3d, 0xc0, 0x55, 0xf1, 0x4d, 0x65, 0x06, 0x2b, 0x89, 0xb2, 0xca, 0xb4, 0xc5, 0x7d, 0x37, 0x74,
	0x62, 0x8f, 0x5f, 0x0e, 0x90, 0xa5, 0x25, 0x0e, 0xfb, 0xa2, 0x4f, 0x07, 0x2e, 0x7e, 0x55, 0x99,
	0x46, 0x49, 0x23, 0xd8, 0x0d, 0x9c, 0xbf, 0x2b, 0xfd, 0x52, 0xab, 0xbc, 0xcc, 0x06, 0x1b, 0xba,
	0x76, 0x8f, 0x9f, 0xf5, 0xd9, 0x60, 0x94, 0xdd, 0x81, 0x4f, 0xba, 0x35, 0x94, 0x15, 0xdb, 0x1c,
	0xe5, 0x70, 0xca, 0xf8, 0x6e, 0x38, 0x8a, 0x3d, 0x3e, 0xed, 0xf2, 0x74, 0x1f, 0x0f, 0x06, 0x0d,
	0xbb, 0x87, 0xc9, 0x5b, 0x5e, 0x63, 0x99, 0xb5, 0x92, 0xb0, 0xf6, 0x47, 0xa1, 0x13, 0x4f, 0x16,
	0x41, 0x62, 0x4d, 0x25, 0xbd, 0xa9, 0x64, 0xd5, 0x9b, 0xe2, 0xd0, 0xe1, 0x4f, 0x7b, 0x7a, 0xf1,
	0x0c, 0x6e, 0xfa, 0xc8, 0x56, 0x70, 0xfa, 0xe3, 0x29, 0xec, 0x3a, 0x39, 0x7c, 0xc0, 0xdf, 0x3a,
	0x83, 0xd9, 0xbf, 0xb9, 0x75, 0x10, 0x1d, 0xad, 0xc7, 0x5d, 0xf7, 0xed, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x29, 0x1a, 0x39, 0x17, 0xcb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CAClient is the client API for CA service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CAClient interface {
	// A request for a time-bound certificate to be signed.
	//
	// The requesting side must provide an id for both loosely based
	// And strong based identities.
	SignCertificate(ctx context.Context, in *SignCertificateRequest, opts ...grpc.CallOption) (*SignCertificateResponse, error)
}

type cAClient struct {
	cc *grpc.ClientConn
}

func NewCAClient(cc *grpc.ClientConn) CAClient {
	return &cAClient{cc}
}

func (c *cAClient) SignCertificate(ctx context.Context, in *SignCertificateRequest, opts ...grpc.CallOption) (*SignCertificateResponse, error) {
	out := new(SignCertificateResponse)
	err := c.cc.Invoke(ctx, "/sentry.CA/SignCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CAServer is the server API for CA service.
type CAServer interface {
	// A request for a time-bound certificate to be signed.
	//
	// The requesting side must provide an id for both loosely based
	// And strong based identities.
	SignCertificate(context.Context, *SignCertificateRequest) (*SignCertificateResponse, error)
}

// UnimplementedCAServer can be embedded to have forward compatible implementations.
type UnimplementedCAServer struct {
}

func (*UnimplementedCAServer) SignCertificate(ctx context.Context, req *SignCertificateRequest) (*SignCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignCertificate not implemented")
}

func RegisterCAServer(s *grpc.Server, srv CAServer) {
	s.RegisterService(&_CA_serviceDesc, srv)
}

func _CA_SignCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CAServer).SignCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sentry.CA/SignCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CAServer).SignCertificate(ctx, req.(*SignCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CA_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sentry.CA",
	HandlerType: (*CAServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignCertificate",
			Handler:    _CA_SignCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentry.proto",
}
