// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/common/v1/internal.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// APIVersion represents the version of Dapr API.
// Dapr and DaprClient service versions follows Dapr API version.
// DaprInternal service version is maintained separately.
type APIVersion int32

const (
	APIVersion_UNKNOWN APIVersion = 0
	APIVersion_V1      APIVersion = 1
)

var APIVersion_name = map[int32]string{
	0: "UNKNOWN",
	1: "V1",
}

var APIVersion_value = map[string]int32{
	"UNKNOWN": 0,
	"V1":      1,
}

func (x APIVersion) String() string {
	return proto.EnumName(APIVersion_name, int32(x))
}

func (APIVersion) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41b900d3b82b7ec9, []int{0}
}

// Status represents the response status for HTTP and gRPC app channel.
type Status struct {
	// The status code
	//
	// This field is required.
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Error message
	//
	// This field is optional.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// A list of messages that carry the error details
	//
	// This field is optional.
	Details              []*any.Any `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_41b900d3b82b7ec9, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetDetails() []*any.Any {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterEnum("pkg.proto.common.v1.APIVersion", APIVersion_name, APIVersion_value)
	proto.RegisterType((*Status)(nil), "pkg.proto.common.v1.Status")
}

func init() {
	proto.RegisterFile("pkg/proto/common/v1/internal.proto", fileDescriptor_41b900d3b82b7ec9)
}

var fileDescriptor_41b900d3b82b7ec9 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0x0b, 0x89, 0xb8, 0x2e, 0x95, 0x61, 0x08, 0x4c, 0xa1, 0x93, 0xd5, 0xc1, 0x56,
	0xe0, 0x17, 0x94, 0x0d, 0x21, 0x05, 0x14, 0x44, 0x91, 0xd8, 0x9c, 0xc6, 0x35, 0x56, 0x13, 0x9f,
	0x65, 0x3b, 0x95, 0xf2, 0xef, 0x11, 0xb1, 0xb2, 0xb1, 0x9c, 0xde, 0xdd, 0x7d, 0xa7, 0x77, 0x0f,
	0x36, 0xf6, 0xa4, 0xb8, 0x75, 0x18, 0x90, 0x1f, 0xb0, 0xef, 0xd1, 0xf0, 0x73, 0xc9, 0xb5, 0x09,
	0xd2, 0x19, 0xd1, 0xb1, 0x69, 0x41, 0x6e, 0xec, 0x49, 0x45, 0xc9, 0x22, 0xc3, 0xce, 0xe5, 0xfd,
	0x9d, 0x42, 0x54, 0x9d, 0x8c, 0xb7, 0xcd, 0x70, 0xe4, 0xc2, 0x8c, 0x11, 0xda, 0x1c, 0x21, 0xfd,
	0x08, 0x22, 0x0c, 0x9e, 0x10, 0xb8, 0x3c, 0x60, 0x2b, 0xf3, 0xa4, 0x48, 0xe8, 0x55, 0x3d, 0x69,
	0x92, 0x43, 0xd6, 0x4b, 0xef, 0x85, 0x92, 0xf9, 0xa2, 0x48, 0xe8, 0x75, 0x3d, 0xb7, 0x84, 0x41,
	0xd6, 0xca, 0x20, 0x74, 0xe7, 0xf3, 0x65, 0xb1, 0xa4, 0xab, 0xc7, 0x5b, 0x16, 0x4d, 0xd8, 0x6c,
	0xc2, 0x76, 0x66, 0xac, 0x67, 0x68, 0xfb, 0x00, 0xb0, 0x7b, 0x7f, 0xd9, 0x4b, 0xe7, 0x35, 0x1a,
	0xb2, 0x82, 0xec, 0xb3, 0x7a, 0xad, 0xde, 0xbe, 0xaa, 0xf5, 0x05, 0x49, 0x61, 0xb1, 0x2f, 0xd7,
	0xc9, 0xf3, 0xf6, 0x9b, 0x2a, 0x1d, 0x7e, 0x86, 0xe6, 0xef, 0x73, 0xde, 0x0a, 0xeb, 0x62, 0xf9,
	0x27, 0x75, 0x93, 0x4e, 0x83, 0xa7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x44, 0xf2, 0x5c, 0x14,
	0x13, 0x01, 0x00, 0x00,
}
