#!/bin/sh
# Copyright 2022 The Dapr Authors
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Patches the k6 executable for the initializer.
# It tries to shutdown the dapr sidecar ASAP when the k6 sub command is `archive`.
# Remove when the following PR https://github.com/grafana/k6-operator/pull/166 is merged and released.
CMD=$(echo "$@" | cut -d " " -f 1)

if [ $CMD == "archive" ]; then
    TOTAL_WAIT=0
    while [[ $TOTAL_WAIT -lt 30 ]] && [[ "$(curl -s -o /dev/null -w ''%{http_code}'' -X POST 127.0.0.1:3500/v1.0/shutdown)" != "204" ]]; do TOTAL_WAIT=$(expr $TOTAL_WAIT + 1);sleep 1; done
fi

exec xk6 "$@"