apiVersion: v1
kind: Service
metadata:
  metadata:
  name: dapr-sidecar-injector
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: dapr-sidecar-injector