apiVersion: actions.io/v1alpha1
kind: Component
metadata:
  name: messagebus
spec:
  type: pubsub.redis
  connectionInfo:
    redisHost: "YOUR_REDIS_HOST_HERE"
    password: "YOUR_REDIS_PASSWORD_HERE"