# current directory must be ./dist

FROM golang:latest AS golang
ENV GOPROXY=https://goproxy.io,direct
RUN CGO_ENABLED=0 go get -ldflags '-s -w -extldflags -static' github.com/go-delve/delve/cmd/dlv

FROM gcr.io/distroless/static:nonroot
ARG PKG_FILES
WORKDIR /
COPY --from=golang /go/bin/dlv /
COPY /$PKG_FILES /