ARG WINDOWS_VERSION=1809
#This version confirmed to work for both github and AKS
FROM ghcr.io/dapr/windows-base:$WINDOWS_VERSION

# Install kubectl using Chocolatey
RUN choco install kubernetes-cli -y

ARG PKG_FILES
WORKDIR /
COPY /$PKG_FILES.exe /

ENTRYPOINT [ "/setup-certificates.cmd", "&", "cmd", "/c" ]