# Note: current directory must be ./dist

ARG MARINER_VERSION=3.0
FROM mcr.microsoft.com/azurelinux/distroless/minimal:${MARINER_VERSION}
ARG PKG_FILES
# The base image specifies the user with its name ("nonroot").
# This is the equivalent UID: Kubernetes requires a numeric ID for "runAsRoot: false" support
USER 65532
WORKDIR /
COPY /$PKG_FILES /
