replicaCount: 1

image:
  repository: actionscore.azurecr.io/actions
  tag: latest
  imagePullPolicy: Always

nameOverride: ""
fullnameOverride: ""

ports:
  protocol: TCP
  port: 80
  targetPort: 6500
  