apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3Rpb25zY29yZS5henVyZWNyLmlvIjp7InVzZXJuYW1lIjoiMzkwNDAxYTctZDdhNi00NmRhLWIxMGYtM2NlZmY3YTFjZGQ1IiwicGFzc3dvcmQiOiI0ODViMzUyMi01OWJiLTQxNTItODkzOC1jYThiOTAxMDhhZjYiLCJlbWFpbCI6Imxpa2FtcmF0QG1pY3Jvc29mdC5jb20iLCJhdXRoIjoiTXprd05EQXhZVGN0WkRkaE5pMDBObVJoTFdJeE1HWXRNMk5sWm1ZM1lURmpaR1ExT2pRNE5XSXpOVEl5TFRVNVltSXROREUxTWkwNE9UTTRMV05oT0dJNU1ERXdPR0ZtTmc9PSJ9fX0=