---
apiVersion: v1
kind: Namespace
metadata:
  name: actions-system
---
# Source: actions-operator/charts/actions_rbac/templates/ServiceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-controller
  namespace: actions-system
---
# Source: actions-operator/charts/actions_crd/templates/components.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.actions.io
  namespace: actions-system
spec:
  group: actions.io
  version: v1alpha1
  names:
    kind: Component
    plural: components
    singular: component
    categories:
    - all
    - actions
  scope: Namespaced
---
# Source: actions-operator/charts/actions_rbac/templates/ClusterRoleBinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: actions-controller
subjects:
- kind: ServiceAccount
  name: actions-controller
  namespace: actions-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# Source: actions-operator/charts/actions_controller/templates/actions_controller_service.yaml
kind: Service
apiVersion: v1
metadata:
  name: actions-api
  namespace: actions-system
spec:
  selector:
    app: actions-controller
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 6500  
---
# Source: actions-operator/charts/actions_placement/templates/actions_placement_service.yaml
kind: Service
apiVersion: v1
metadata:
  name: actions-placement
  namespace: actions-system
spec:
  selector:
    app: actions-placement
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 50005

---
# Source: actions-operator/charts/actions_controller/templates/actions_controller_deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-controller
  namespace: actions-system
  labels:
    app: actions-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-controller
  template:
    metadata:
      labels:
        app: actions-controller
    spec:
      containers:
      - name: actions-controller
        repository: 
        image: "actionscore.azurecr.io/actions:latest"
        env:
        - name: RUNTIME_IMAGE
          value: "actionscore.azurecr.io/actions:latest"
        - name: NAMESPACE
          value: actions-system
        imagePullPolicy: 
        ports:
        - containerPort: 6500
        command: ["./controller"]
      serviceAccountName: actions-controller            

---
# Source: actions-operator/charts/actions_placement/templates/actions_placement_deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-placement
  namespace: actions-system
  labels:
    app: actions-placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-placement
  template:
    metadata:
      labels:
        app: actions-placement
    spec:
      containers:
      - name: actions-placement
        repository: 
        image: "actionscore.azurecr.io/actions:latest"
        imagePullPolicy: 
        ports:
          - containerPort: 50005
        command: ["./placement"]
      serviceAccountName: actions-controller