apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.actions.io
spec:
  group: actions.io
  version: v1alpha1
  names:
    kind: Component
    plural: components
    singular: components
    categories:
    - all
    - actions
  scope: Namespaced
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: actions-controller
  namespace: default

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: actions-controller
subjects:
- kind: ServiceAccount
  name: actions-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
kind: Service
apiVersion: v1
metadata:
  name: actions-api
spec:
  selector:
    app: actions-controller
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-controller
  labels:
    app: actions-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-controller
  template:
    metadata:
      labels:
        app: actions-controller
    spec:
      containers:
      - name: actions-controller
        image: actionscore.azurecr.io/actions:merge
        env:
        - name: RUNTIME_IMAGE
          value: actionscore.azurecr.io/actions:merge
        imagePullPolicy: Always
        ports:
        - containerPort: 6500
        command: ["./controller"]
      imagePullSecrets:
      - name: actions-auth
      serviceAccountName: actions-controller

---
kind: Service
apiVersion: v1
metadata:
  name: actions-placement
spec:
  selector:
    app: actions-placement
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-placement
  labels:
    app: actions-placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-placement
  template:
    metadata:
      labels:
        app: actions-placement
    spec:
      containers:
      - name: actions-placement
        image: actionscore.azurecr.io/actions:merge
        imagePullPolicy: Always
        ports:
        - containerPort: 50005
        command: ["./placement"]
      imagePullSecrets:
      - name: actions-auth
      serviceAccountName: actions-controller
