// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dapr/proto/runtime/v1/dapr.proto

package runtime

import (
	context "context"
	fmt "fmt"
	v1 "github.com/dapr/dapr/pkg/proto/common/v1"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InvokeServiceRequest represents the request message for Service invocation.
type InvokeServiceRequest struct {
	// Required. Callee's app id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Required. message which will be delivered to callee.
	Message              *v1.InvokeRequest `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeServiceRequest) Reset()         { *m = InvokeServiceRequest{} }
func (m *InvokeServiceRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeServiceRequest) ProtoMessage()    {}
func (*InvokeServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{0}
}

func (m *InvokeServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeServiceRequest.Unmarshal(m, b)
}
func (m *InvokeServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeServiceRequest.Marshal(b, m, deterministic)
}
func (m *InvokeServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeServiceRequest.Merge(m, src)
}
func (m *InvokeServiceRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeServiceRequest.Size(m)
}
func (m *InvokeServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeServiceRequest proto.InternalMessageInfo

func (m *InvokeServiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InvokeServiceRequest) GetMessage() *v1.InvokeRequest {
	if m != nil {
		return m.Message
	}
	return nil
}

// GetStateRequest is the message to get key-value states from specific state store.
type GetStateRequest struct {
	// The name of state store.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// The key of the desired state
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The read consistency of the state store.
	Consistency v1.StateOptions_StateConsistency `protobuf:"varint,3,opt,name=consistency,proto3,enum=dapr.proto.common.v1.StateOptions_StateConsistency" json:"consistency,omitempty"`
	// The metadata which will be sent to state store components.
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStateRequest) Reset()         { *m = GetStateRequest{} }
func (m *GetStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetStateRequest) ProtoMessage()    {}
func (*GetStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{1}
}

func (m *GetStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateRequest.Unmarshal(m, b)
}
func (m *GetStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateRequest.Marshal(b, m, deterministic)
}
func (m *GetStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateRequest.Merge(m, src)
}
func (m *GetStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetStateRequest.Size(m)
}
func (m *GetStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateRequest proto.InternalMessageInfo

func (m *GetStateRequest) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *GetStateRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetStateRequest) GetConsistency() v1.StateOptions_StateConsistency {
	if m != nil {
		return m.Consistency
	}
	return v1.StateOptions_CONSISTENCY_UNSPECIFIED
}

func (m *GetStateRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetBulkStateRequest is the message to get a list of key-value states from specific state store.
type GetBulkStateRequest struct {
	// The name of state store.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// The keys to get.
	Keys []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	// The number of parallel operations executed on the state store for a get operation.
	Parallelism int32 `protobuf:"varint,3,opt,name=parallelism,proto3" json:"parallelism,omitempty"`
	// The metadata which will be sent to state store components.
	Metadata             map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetBulkStateRequest) Reset()         { *m = GetBulkStateRequest{} }
func (m *GetBulkStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetBulkStateRequest) ProtoMessage()    {}
func (*GetBulkStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{2}
}

func (m *GetBulkStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBulkStateRequest.Unmarshal(m, b)
}
func (m *GetBulkStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBulkStateRequest.Marshal(b, m, deterministic)
}
func (m *GetBulkStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBulkStateRequest.Merge(m, src)
}
func (m *GetBulkStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetBulkStateRequest.Size(m)
}
func (m *GetBulkStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBulkStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBulkStateRequest proto.InternalMessageInfo

func (m *GetBulkStateRequest) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *GetBulkStateRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetBulkStateRequest) GetParallelism() int32 {
	if m != nil {
		return m.Parallelism
	}
	return 0
}

func (m *GetBulkStateRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetBulkStateResponse is the response conveying the list of state values.
type GetBulkStateResponse struct {
	// The list of items containing the keys to get values for.
	Items                []*BulkStateItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetBulkStateResponse) Reset()         { *m = GetBulkStateResponse{} }
func (m *GetBulkStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetBulkStateResponse) ProtoMessage()    {}
func (*GetBulkStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{3}
}

func (m *GetBulkStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBulkStateResponse.Unmarshal(m, b)
}
func (m *GetBulkStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBulkStateResponse.Marshal(b, m, deterministic)
}
func (m *GetBulkStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBulkStateResponse.Merge(m, src)
}
func (m *GetBulkStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetBulkStateResponse.Size(m)
}
func (m *GetBulkStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBulkStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBulkStateResponse proto.InternalMessageInfo

func (m *GetBulkStateResponse) GetItems() []*BulkStateItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// BulkStateItem is the response item for a bulk get operation.
// Return values include the item key, data and etag.
type BulkStateItem struct {
	// state item key
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The byte array data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The entity tag which represents the specific version of data.
	// ETag format is defined by the corresponding data store.
	Etag string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	// The error that was returned from the state store in case of a failed get operation.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// The metadata which will be sent to app.
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BulkStateItem) Reset()         { *m = BulkStateItem{} }
func (m *BulkStateItem) String() string { return proto.CompactTextString(m) }
func (*BulkStateItem) ProtoMessage()    {}
func (*BulkStateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{4}
}

func (m *BulkStateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BulkStateItem.Unmarshal(m, b)
}
func (m *BulkStateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BulkStateItem.Marshal(b, m, deterministic)
}
func (m *BulkStateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BulkStateItem.Merge(m, src)
}
func (m *BulkStateItem) XXX_Size() int {
	return xxx_messageInfo_BulkStateItem.Size(m)
}
func (m *BulkStateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_BulkStateItem.DiscardUnknown(m)
}

var xxx_messageInfo_BulkStateItem proto.InternalMessageInfo

func (m *BulkStateItem) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *BulkStateItem) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *BulkStateItem) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *BulkStateItem) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BulkStateItem) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetStateResponse is the response conveying the state value and etag.
type GetStateResponse struct {
	// The byte array data
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The entity tag which represents the specific version of data.
	// ETag format is defined by the corresponding data store.
	Etag string `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	// The metadata which will be sent to app.
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetStateResponse) Reset()         { *m = GetStateResponse{} }
func (m *GetStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetStateResponse) ProtoMessage()    {}
func (*GetStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{5}
}

func (m *GetStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStateResponse.Unmarshal(m, b)
}
func (m *GetStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStateResponse.Marshal(b, m, deterministic)
}
func (m *GetStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStateResponse.Merge(m, src)
}
func (m *GetStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetStateResponse.Size(m)
}
func (m *GetStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStateResponse proto.InternalMessageInfo

func (m *GetStateResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetStateResponse) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *GetStateResponse) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// DeleteStateRequest is the message to delete key-value states in the specific state store.
type DeleteStateRequest struct {
	// The name of state store.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// The key of the desired state
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The entity tag which represents the specific version of data.
	// The exact ETag format is defined by the corresponding data store.
	Etag string `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`
	// State operation options which includes concurrency/
	// consistency/retry_policy.
	Options *v1.StateOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	// The metadata which will be sent to state store components.
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DeleteStateRequest) Reset()         { *m = DeleteStateRequest{} }
func (m *DeleteStateRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStateRequest) ProtoMessage()    {}
func (*DeleteStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{6}
}

func (m *DeleteStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStateRequest.Unmarshal(m, b)
}
func (m *DeleteStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStateRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStateRequest.Merge(m, src)
}
func (m *DeleteStateRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStateRequest.Size(m)
}
func (m *DeleteStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStateRequest proto.InternalMessageInfo

func (m *DeleteStateRequest) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *DeleteStateRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteStateRequest) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *DeleteStateRequest) GetOptions() *v1.StateOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *DeleteStateRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// SaveStateRequest is the message to save multiple states into state store.
type SaveStateRequest struct {
	// The name of state store.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// The array of the state key values.
	States               []*v1.StateItem `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SaveStateRequest) Reset()         { *m = SaveStateRequest{} }
func (m *SaveStateRequest) String() string { return proto.CompactTextString(m) }
func (*SaveStateRequest) ProtoMessage()    {}
func (*SaveStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{7}
}

func (m *SaveStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveStateRequest.Unmarshal(m, b)
}
func (m *SaveStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveStateRequest.Marshal(b, m, deterministic)
}
func (m *SaveStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveStateRequest.Merge(m, src)
}
func (m *SaveStateRequest) XXX_Size() int {
	return xxx_messageInfo_SaveStateRequest.Size(m)
}
func (m *SaveStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveStateRequest proto.InternalMessageInfo

func (m *SaveStateRequest) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *SaveStateRequest) GetStates() []*v1.StateItem {
	if m != nil {
		return m.States
	}
	return nil
}

// PublishEventRequest is the message to publish event data to pubsub topic
type PublishEventRequest struct {
	// The name of the pubsub component
	PubsubName string `protobuf:"bytes,1,opt,name=pubsub_name,json=pubsubName,proto3" json:"pubsub_name,omitempty"`
	// The pubsub topic
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	// The data which will be published to topic.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// The content type for the data (optional).
	DataContentType string `protobuf:"bytes,4,opt,name=data_content_type,json=dataContentType,proto3" json:"data_content_type,omitempty"`
	// The metadata passing to pub components
	//
	// metadata property:
	// - key : the key of the message.
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PublishEventRequest) Reset()         { *m = PublishEventRequest{} }
func (m *PublishEventRequest) String() string { return proto.CompactTextString(m) }
func (*PublishEventRequest) ProtoMessage()    {}
func (*PublishEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{8}
}

func (m *PublishEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishEventRequest.Unmarshal(m, b)
}
func (m *PublishEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishEventRequest.Marshal(b, m, deterministic)
}
func (m *PublishEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishEventRequest.Merge(m, src)
}
func (m *PublishEventRequest) XXX_Size() int {
	return xxx_messageInfo_PublishEventRequest.Size(m)
}
func (m *PublishEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishEventRequest proto.InternalMessageInfo

func (m *PublishEventRequest) GetPubsubName() string {
	if m != nil {
		return m.PubsubName
	}
	return ""
}

func (m *PublishEventRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PublishEventRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PublishEventRequest) GetDataContentType() string {
	if m != nil {
		return m.DataContentType
	}
	return ""
}

func (m *PublishEventRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// InvokeBindingRequest is the message to send data to output bindings
type InvokeBindingRequest struct {
	// The name of the output binding to invoke.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The data which will be sent to output binding.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// The metadata passing to output binding components
	//
	// Common metadata property:
	// - ttlInSeconds : the time to live in seconds for the message.
	// If set in the binding definition will cause all messages to
	// have a default time to live. The message ttl overrides any value
	// in the binding definition.
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The name of the operation type for the binding to invoke
	Operation            string   `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeBindingRequest) Reset()         { *m = InvokeBindingRequest{} }
func (m *InvokeBindingRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeBindingRequest) ProtoMessage()    {}
func (*InvokeBindingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{9}
}

func (m *InvokeBindingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeBindingRequest.Unmarshal(m, b)
}
func (m *InvokeBindingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeBindingRequest.Marshal(b, m, deterministic)
}
func (m *InvokeBindingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeBindingRequest.Merge(m, src)
}
func (m *InvokeBindingRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeBindingRequest.Size(m)
}
func (m *InvokeBindingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeBindingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeBindingRequest proto.InternalMessageInfo

func (m *InvokeBindingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InvokeBindingRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InvokeBindingRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *InvokeBindingRequest) GetOperation() string {
	if m != nil {
		return m.Operation
	}
	return ""
}

// InvokeBindingResponse is the message returned from an output binding invocation
type InvokeBindingResponse struct {
	// The data which will be sent to output binding.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The metadata returned from an external system
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeBindingResponse) Reset()         { *m = InvokeBindingResponse{} }
func (m *InvokeBindingResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeBindingResponse) ProtoMessage()    {}
func (*InvokeBindingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{10}
}

func (m *InvokeBindingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeBindingResponse.Unmarshal(m, b)
}
func (m *InvokeBindingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeBindingResponse.Marshal(b, m, deterministic)
}
func (m *InvokeBindingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeBindingResponse.Merge(m, src)
}
func (m *InvokeBindingResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeBindingResponse.Size(m)
}
func (m *InvokeBindingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeBindingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeBindingResponse proto.InternalMessageInfo

func (m *InvokeBindingResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *InvokeBindingResponse) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetSecretRequest is the message to get secret from secret store.
type GetSecretRequest struct {
	// The name of secret store.
	StoreName string `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	// The name of secret key.
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// The metadata which will be sent to secret store components.
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSecretRequest) Reset()         { *m = GetSecretRequest{} }
func (m *GetSecretRequest) String() string { return proto.CompactTextString(m) }
func (*GetSecretRequest) ProtoMessage()    {}
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{11}
}

func (m *GetSecretRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretRequest.Unmarshal(m, b)
}
func (m *GetSecretRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretRequest.Marshal(b, m, deterministic)
}
func (m *GetSecretRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretRequest.Merge(m, src)
}
func (m *GetSecretRequest) XXX_Size() int {
	return xxx_messageInfo_GetSecretRequest.Size(m)
}
func (m *GetSecretRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretRequest proto.InternalMessageInfo

func (m *GetSecretRequest) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *GetSecretRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetSecretRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// GetSecretResponse is the response message to convey the requested secret.
type GetSecretResponse struct {
	// data is the secret value. Some secret store, such as kubernetes secret
	// store, can save multiple secrets for single secret key.
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetSecretResponse) Reset()         { *m = GetSecretResponse{} }
func (m *GetSecretResponse) String() string { return proto.CompactTextString(m) }
func (*GetSecretResponse) ProtoMessage()    {}
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{12}
}

func (m *GetSecretResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSecretResponse.Unmarshal(m, b)
}
func (m *GetSecretResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSecretResponse.Marshal(b, m, deterministic)
}
func (m *GetSecretResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSecretResponse.Merge(m, src)
}
func (m *GetSecretResponse) XXX_Size() int {
	return xxx_messageInfo_GetSecretResponse.Size(m)
}
func (m *GetSecretResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSecretResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSecretResponse proto.InternalMessageInfo

func (m *GetSecretResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

// TransactionalStateOperation is the message to execute a specified operation with a key-value pair.
type TransactionalStateOperation struct {
	// The type of operation to be executed
	OperationType string `protobuf:"bytes,1,opt,name=operationType,proto3" json:"operationType,omitempty"`
	// State values to be operated on
	Request              *v1.StateItem `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TransactionalStateOperation) Reset()         { *m = TransactionalStateOperation{} }
func (m *TransactionalStateOperation) String() string { return proto.CompactTextString(m) }
func (*TransactionalStateOperation) ProtoMessage()    {}
func (*TransactionalStateOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{13}
}

func (m *TransactionalStateOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionalStateOperation.Unmarshal(m, b)
}
func (m *TransactionalStateOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionalStateOperation.Marshal(b, m, deterministic)
}
func (m *TransactionalStateOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionalStateOperation.Merge(m, src)
}
func (m *TransactionalStateOperation) XXX_Size() int {
	return xxx_messageInfo_TransactionalStateOperation.Size(m)
}
func (m *TransactionalStateOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionalStateOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionalStateOperation proto.InternalMessageInfo

func (m *TransactionalStateOperation) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *TransactionalStateOperation) GetRequest() *v1.StateItem {
	if m != nil {
		return m.Request
	}
	return nil
}

// ExecuteStateTransactionRequest is the message to execute multiple operations on a specified store.
type ExecuteStateTransactionRequest struct {
	// Required. name of state store.
	StoreName string `protobuf:"bytes,1,opt,name=storeName,proto3" json:"storeName,omitempty"`
	// Required. transactional operation list.
	Operations []*TransactionalStateOperation `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	// The metadata used for transactional operations.
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExecuteStateTransactionRequest) Reset()         { *m = ExecuteStateTransactionRequest{} }
func (m *ExecuteStateTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStateTransactionRequest) ProtoMessage()    {}
func (*ExecuteStateTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{14}
}

func (m *ExecuteStateTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStateTransactionRequest.Unmarshal(m, b)
}
func (m *ExecuteStateTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStateTransactionRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteStateTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStateTransactionRequest.Merge(m, src)
}
func (m *ExecuteStateTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteStateTransactionRequest.Size(m)
}
func (m *ExecuteStateTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStateTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStateTransactionRequest proto.InternalMessageInfo

func (m *ExecuteStateTransactionRequest) GetStoreName() string {
	if m != nil {
		return m.StoreName
	}
	return ""
}

func (m *ExecuteStateTransactionRequest) GetOperations() []*TransactionalStateOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

func (m *ExecuteStateTransactionRequest) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// RegisterActorTimerRequest is the message to register a timer for an actor of a given type and id.
type RegisterActorTimerRequest struct {
	ActorType            string   `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DueTime              string   `protobuf:"bytes,4,opt,name=due_time,json=dueTime,proto3" json:"due_time,omitempty"`
	Period               string   `protobuf:"bytes,5,opt,name=period,proto3" json:"period,omitempty"`
	Callback             string   `protobuf:"bytes,6,opt,name=callback,proto3" json:"callback,omitempty"`
	Data                 []byte   `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterActorTimerRequest) Reset()         { *m = RegisterActorTimerRequest{} }
func (m *RegisterActorTimerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterActorTimerRequest) ProtoMessage()    {}
func (*RegisterActorTimerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{15}
}

func (m *RegisterActorTimerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterActorTimerRequest.Unmarshal(m, b)
}
func (m *RegisterActorTimerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterActorTimerRequest.Marshal(b, m, deterministic)
}
func (m *RegisterActorTimerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterActorTimerRequest.Merge(m, src)
}
func (m *RegisterActorTimerRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterActorTimerRequest.Size(m)
}
func (m *RegisterActorTimerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterActorTimerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterActorTimerRequest proto.InternalMessageInfo

func (m *RegisterActorTimerRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *RegisterActorTimerRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *RegisterActorTimerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterActorTimerRequest) GetDueTime() string {
	if m != nil {
		return m.DueTime
	}
	return ""
}

func (m *RegisterActorTimerRequest) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *RegisterActorTimerRequest) GetCallback() string {
	if m != nil {
		return m.Callback
	}
	return ""
}

func (m *RegisterActorTimerRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// UnregisterActorTimerRequest is the message to unregister an actor timer
type UnregisterActorTimerRequest struct {
	ActorType            string   `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterActorTimerRequest) Reset()         { *m = UnregisterActorTimerRequest{} }
func (m *UnregisterActorTimerRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterActorTimerRequest) ProtoMessage()    {}
func (*UnregisterActorTimerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{16}
}

func (m *UnregisterActorTimerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterActorTimerRequest.Unmarshal(m, b)
}
func (m *UnregisterActorTimerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterActorTimerRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterActorTimerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterActorTimerRequest.Merge(m, src)
}
func (m *UnregisterActorTimerRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterActorTimerRequest.Size(m)
}
func (m *UnregisterActorTimerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterActorTimerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterActorTimerRequest proto.InternalMessageInfo

func (m *UnregisterActorTimerRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *UnregisterActorTimerRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *UnregisterActorTimerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// RegisterActorReminderRequest is the message to register a reminder for an actor of a given type and id.
type RegisterActorReminderRequest struct {
	ActorType            string   `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DueTime              string   `protobuf:"bytes,4,opt,name=due_time,json=dueTime,proto3" json:"due_time,omitempty"`
	Period               string   `protobuf:"bytes,5,opt,name=period,proto3" json:"period,omitempty"`
	Data                 []byte   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterActorReminderRequest) Reset()         { *m = RegisterActorReminderRequest{} }
func (m *RegisterActorReminderRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterActorReminderRequest) ProtoMessage()    {}
func (*RegisterActorReminderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{17}
}

func (m *RegisterActorReminderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterActorReminderRequest.Unmarshal(m, b)
}
func (m *RegisterActorReminderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterActorReminderRequest.Marshal(b, m, deterministic)
}
func (m *RegisterActorReminderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterActorReminderRequest.Merge(m, src)
}
func (m *RegisterActorReminderRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterActorReminderRequest.Size(m)
}
func (m *RegisterActorReminderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterActorReminderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterActorReminderRequest proto.InternalMessageInfo

func (m *RegisterActorReminderRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *RegisterActorReminderRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *RegisterActorReminderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterActorReminderRequest) GetDueTime() string {
	if m != nil {
		return m.DueTime
	}
	return ""
}

func (m *RegisterActorReminderRequest) GetPeriod() string {
	if m != nil {
		return m.Period
	}
	return ""
}

func (m *RegisterActorReminderRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// UnregisterActorReminderRequest is the message to unregister an actor reminder.
type UnregisterActorReminderRequest struct {
	ActorType            string   `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterActorReminderRequest) Reset()         { *m = UnregisterActorReminderRequest{} }
func (m *UnregisterActorReminderRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterActorReminderRequest) ProtoMessage()    {}
func (*UnregisterActorReminderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{18}
}

func (m *UnregisterActorReminderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterActorReminderRequest.Unmarshal(m, b)
}
func (m *UnregisterActorReminderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterActorReminderRequest.Marshal(b, m, deterministic)
}
func (m *UnregisterActorReminderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterActorReminderRequest.Merge(m, src)
}
func (m *UnregisterActorReminderRequest) XXX_Size() int {
	return xxx_messageInfo_UnregisterActorReminderRequest.Size(m)
}
func (m *UnregisterActorReminderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterActorReminderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterActorReminderRequest proto.InternalMessageInfo

func (m *UnregisterActorReminderRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *UnregisterActorReminderRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *UnregisterActorReminderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// GetActorStateRequest is the message to get key-value states from specific actor.
type GetActorStateRequest struct {
	ActorType            string   `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActorStateRequest) Reset()         { *m = GetActorStateRequest{} }
func (m *GetActorStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetActorStateRequest) ProtoMessage()    {}
func (*GetActorStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{19}
}

func (m *GetActorStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActorStateRequest.Unmarshal(m, b)
}
func (m *GetActorStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActorStateRequest.Marshal(b, m, deterministic)
}
func (m *GetActorStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActorStateRequest.Merge(m, src)
}
func (m *GetActorStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetActorStateRequest.Size(m)
}
func (m *GetActorStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActorStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActorStateRequest proto.InternalMessageInfo

func (m *GetActorStateRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *GetActorStateRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *GetActorStateRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// GetActorStateResponse is the response conveying the actor's state value.
type GetActorStateResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActorStateResponse) Reset()         { *m = GetActorStateResponse{} }
func (m *GetActorStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetActorStateResponse) ProtoMessage()    {}
func (*GetActorStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{20}
}

func (m *GetActorStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActorStateResponse.Unmarshal(m, b)
}
func (m *GetActorStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActorStateResponse.Marshal(b, m, deterministic)
}
func (m *GetActorStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActorStateResponse.Merge(m, src)
}
func (m *GetActorStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetActorStateResponse.Size(m)
}
func (m *GetActorStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActorStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetActorStateResponse proto.InternalMessageInfo

func (m *GetActorStateResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// ExecuteActorStateTransactionRequest is the message to execute multiple operations on a specified actor.
type ExecuteActorStateTransactionRequest struct {
	ActorType            string                              `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string                              `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Operations           []*TransactionalActorStateOperation `protobuf:"bytes,3,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ExecuteActorStateTransactionRequest) Reset()         { *m = ExecuteActorStateTransactionRequest{} }
func (m *ExecuteActorStateTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteActorStateTransactionRequest) ProtoMessage()    {}
func (*ExecuteActorStateTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{21}
}

func (m *ExecuteActorStateTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteActorStateTransactionRequest.Unmarshal(m, b)
}
func (m *ExecuteActorStateTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteActorStateTransactionRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteActorStateTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteActorStateTransactionRequest.Merge(m, src)
}
func (m *ExecuteActorStateTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteActorStateTransactionRequest.Size(m)
}
func (m *ExecuteActorStateTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteActorStateTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteActorStateTransactionRequest proto.InternalMessageInfo

func (m *ExecuteActorStateTransactionRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *ExecuteActorStateTransactionRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *ExecuteActorStateTransactionRequest) GetOperations() []*TransactionalActorStateOperation {
	if m != nil {
		return m.Operations
	}
	return nil
}

// TransactionalAcorStateOperation is the message to execute a specified operation with a key-value pair.
type TransactionalActorStateOperation struct {
	OperationType        string   `protobuf:"bytes,1,opt,name=operationType,proto3" json:"operationType,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *any.Any `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionalActorStateOperation) Reset()         { *m = TransactionalActorStateOperation{} }
func (m *TransactionalActorStateOperation) String() string { return proto.CompactTextString(m) }
func (*TransactionalActorStateOperation) ProtoMessage()    {}
func (*TransactionalActorStateOperation) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{22}
}

func (m *TransactionalActorStateOperation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionalActorStateOperation.Unmarshal(m, b)
}
func (m *TransactionalActorStateOperation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionalActorStateOperation.Marshal(b, m, deterministic)
}
func (m *TransactionalActorStateOperation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionalActorStateOperation.Merge(m, src)
}
func (m *TransactionalActorStateOperation) XXX_Size() int {
	return xxx_messageInfo_TransactionalActorStateOperation.Size(m)
}
func (m *TransactionalActorStateOperation) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionalActorStateOperation.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionalActorStateOperation proto.InternalMessageInfo

func (m *TransactionalActorStateOperation) GetOperationType() string {
	if m != nil {
		return m.OperationType
	}
	return ""
}

func (m *TransactionalActorStateOperation) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *TransactionalActorStateOperation) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

// InvokeActorRequest is the message to call an actor.
type InvokeActorRequest struct {
	ActorType            string   `protobuf:"bytes,1,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	ActorId              string   `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Method               string   `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeActorRequest) Reset()         { *m = InvokeActorRequest{} }
func (m *InvokeActorRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeActorRequest) ProtoMessage()    {}
func (*InvokeActorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{23}
}

func (m *InvokeActorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeActorRequest.Unmarshal(m, b)
}
func (m *InvokeActorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeActorRequest.Marshal(b, m, deterministic)
}
func (m *InvokeActorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeActorRequest.Merge(m, src)
}
func (m *InvokeActorRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeActorRequest.Size(m)
}
func (m *InvokeActorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeActorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeActorRequest proto.InternalMessageInfo

func (m *InvokeActorRequest) GetActorType() string {
	if m != nil {
		return m.ActorType
	}
	return ""
}

func (m *InvokeActorRequest) GetActorId() string {
	if m != nil {
		return m.ActorId
	}
	return ""
}

func (m *InvokeActorRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *InvokeActorRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// InvokeActorResponse is the method that returns an actor invocation response.
type InvokeActorResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeActorResponse) Reset()         { *m = InvokeActorResponse{} }
func (m *InvokeActorResponse) String() string { return proto.CompactTextString(m) }
func (*InvokeActorResponse) ProtoMessage()    {}
func (*InvokeActorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_da511bac0105b1e5, []int{24}
}

func (m *InvokeActorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeActorResponse.Unmarshal(m, b)
}
func (m *InvokeActorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeActorResponse.Marshal(b, m, deterministic)
}
func (m *InvokeActorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeActorResponse.Merge(m, src)
}
func (m *InvokeActorResponse) XXX_Size() int {
	return xxx_messageInfo_InvokeActorResponse.Size(m)
}
func (m *InvokeActorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeActorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeActorResponse proto.InternalMessageInfo

func (m *InvokeActorResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*InvokeServiceRequest)(nil), "dapr.proto.runtime.v1.InvokeServiceRequest")
	proto.RegisterType((*GetStateRequest)(nil), "dapr.proto.runtime.v1.GetStateRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.GetStateRequest.MetadataEntry")
	proto.RegisterType((*GetBulkStateRequest)(nil), "dapr.proto.runtime.v1.GetBulkStateRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.GetBulkStateRequest.MetadataEntry")
	proto.RegisterType((*GetBulkStateResponse)(nil), "dapr.proto.runtime.v1.GetBulkStateResponse")
	proto.RegisterType((*BulkStateItem)(nil), "dapr.proto.runtime.v1.BulkStateItem")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.BulkStateItem.MetadataEntry")
	proto.RegisterType((*GetStateResponse)(nil), "dapr.proto.runtime.v1.GetStateResponse")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.GetStateResponse.MetadataEntry")
	proto.RegisterType((*DeleteStateRequest)(nil), "dapr.proto.runtime.v1.DeleteStateRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.DeleteStateRequest.MetadataEntry")
	proto.RegisterType((*SaveStateRequest)(nil), "dapr.proto.runtime.v1.SaveStateRequest")
	proto.RegisterType((*PublishEventRequest)(nil), "dapr.proto.runtime.v1.PublishEventRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.PublishEventRequest.MetadataEntry")
	proto.RegisterType((*InvokeBindingRequest)(nil), "dapr.proto.runtime.v1.InvokeBindingRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.InvokeBindingRequest.MetadataEntry")
	proto.RegisterType((*InvokeBindingResponse)(nil), "dapr.proto.runtime.v1.InvokeBindingResponse")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.InvokeBindingResponse.MetadataEntry")
	proto.RegisterType((*GetSecretRequest)(nil), "dapr.proto.runtime.v1.GetSecretRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.GetSecretRequest.MetadataEntry")
	proto.RegisterType((*GetSecretResponse)(nil), "dapr.proto.runtime.v1.GetSecretResponse")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.GetSecretResponse.DataEntry")
	proto.RegisterType((*TransactionalStateOperation)(nil), "dapr.proto.runtime.v1.TransactionalStateOperation")
	proto.RegisterType((*ExecuteStateTransactionRequest)(nil), "dapr.proto.runtime.v1.ExecuteStateTransactionRequest")
	proto.RegisterMapType((map[string]string)(nil), "dapr.proto.runtime.v1.ExecuteStateTransactionRequest.MetadataEntry")
	proto.RegisterType((*RegisterActorTimerRequest)(nil), "dapr.proto.runtime.v1.RegisterActorTimerRequest")
	proto.RegisterType((*UnregisterActorTimerRequest)(nil), "dapr.proto.runtime.v1.UnregisterActorTimerRequest")
	proto.RegisterType((*RegisterActorReminderRequest)(nil), "dapr.proto.runtime.v1.RegisterActorReminderRequest")
	proto.RegisterType((*UnregisterActorReminderRequest)(nil), "dapr.proto.runtime.v1.UnregisterActorReminderRequest")
	proto.RegisterType((*GetActorStateRequest)(nil), "dapr.proto.runtime.v1.GetActorStateRequest")
	proto.RegisterType((*GetActorStateResponse)(nil), "dapr.proto.runtime.v1.GetActorStateResponse")
	proto.RegisterType((*ExecuteActorStateTransactionRequest)(nil), "dapr.proto.runtime.v1.ExecuteActorStateTransactionRequest")
	proto.RegisterType((*TransactionalActorStateOperation)(nil), "dapr.proto.runtime.v1.TransactionalActorStateOperation")
	proto.RegisterType((*InvokeActorRequest)(nil), "dapr.proto.runtime.v1.InvokeActorRequest")
	proto.RegisterType((*InvokeActorResponse)(nil), "dapr.proto.runtime.v1.InvokeActorResponse")
}

func init() { proto.RegisterFile("dapr/proto/runtime/v1/dapr.proto", fileDescriptor_da511bac0105b1e5) }

var fileDescriptor_da511bac0105b1e5 = []byte{
	// 1448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0xcb, 0x6f, 0xdc, 0x44,
	0x18, 0x8f, 0xf7, 0x91, 0x64, 0xbf, 0x4d, 0xfa, 0x98, 0x26, 0x65, 0xb3, 0x09, 0xed, 0xe2, 0x56,
	0x34, 0x4d, 0x91, 0xc3, 0x6e, 0xa9, 0xda, 0xa6, 0x70, 0x68, 0x1e, 0x54, 0x3d, 0x50, 0x8a, 0x93,
	0x82, 0x84, 0x84, 0x82, 0xd7, 0x9e, 0x6e, 0xdd, 0xf5, 0x0b, 0x7b, 0xbc, 0x62, 0x39, 0x70, 0xe4,
	0x2f, 0xe0, 0xce, 0x15, 0x38, 0x21, 0x71, 0xe1, 0xc8, 0x19, 0x71, 0x83, 0x3f, 0x83, 0x03, 0xff,
	0x00, 0x12, 0xf2, 0xcc, 0xd8, 0x6b, 0xaf, 0x1f, 0x71, 0x52, 0x2d, 0xe2, 0x92, 0xcc, 0xeb, 0x9b,
	0xef, 0xf7, 0x3d, 0xe6, 0xf7, 0xcd, 0x78, 0xa1, 0xa3, 0x29, 0x8e, 0xbb, 0xed, 0xb8, 0x36, 0xb1,
	0xb7, 0x5d, 0xdf, 0x22, 0xba, 0x89, 0xb7, 0x47, 0xdd, 0xed, 0x60, 0x54, 0xa2, 0xa3, 0x68, 0x75,
	0xd2, 0x96, 0xf8, 0x0a, 0x69, 0xd4, 0x6d, 0xaf, 0x0d, 0x6c, 0x7b, 0x60, 0x60, 0x26, 0xda, 0xf7,
	0x9f, 0x6f, 0x2b, 0xd6, 0x98, 0xad, 0x6a, 0xaf, 0x4f, 0x4f, 0x61, 0xd3, 0x21, 0xe1, 0xe4, 0x1b,
	0x31, 0x85, 0xaa, 0x6d, 0x9a, 0xb6, 0x15, 0xe8, 0x63, 0x2d, 0xb6, 0x44, 0xc4, 0xb0, 0xf2, 0xd8,
	0x1a, 0xd9, 0x43, 0x7c, 0x88, 0xdd, 0x91, 0xae, 0x62, 0x19, 0x7f, 0xe1, 0x63, 0x8f, 0xa0, 0x73,
	0x50, 0xd1, 0xb5, 0x96, 0xd0, 0x11, 0x36, 0x1b, 0x72, 0x45, 0xd7, 0xd0, 0x7b, 0xb0, 0x60, 0x62,
	0xcf, 0x53, 0x06, 0xb8, 0x55, 0xed, 0x08, 0x9b, 0xcd, 0xde, 0x35, 0x29, 0x86, 0x95, 0x6f, 0x39,
	0xea, 0x4a, 0x6c, 0x33, 0xbe, 0x8b, 0x1c, 0xca, 0x88, 0xdf, 0x57, 0xe0, 0xfc, 0x23, 0x4c, 0x0e,
	0x89, 0x42, 0x22, 0x15, 0xaf, 0x03, 0x78, 0xc4, 0x76, 0xf1, 0xb1, 0xa5, 0x98, 0x98, 0xab, 0x6a,
	0xd0, 0x91, 0x27, 0x8a, 0x89, 0xd1, 0x05, 0xa8, 0x0e, 0xf1, 0xb8, 0x55, 0xa1, 0xe3, 0x41, 0x13,
	0x3d, 0x83, 0xa6, 0x6a, 0x5b, 0x9e, 0xee, 0x11, 0x6c, 0xa9, 0x63, 0x8a, 0xe3, 0x5c, 0xef, 0x76,
	0x36, 0x0e, 0xaa, 0xe9, 0x43, 0x87, 0xe8, 0xb6, 0xe5, 0xb1, 0xce, 0xde, 0x44, 0x54, 0x8e, 0xef,
	0x83, 0x9e, 0xc2, 0xa2, 0x89, 0x89, 0xa2, 0x29, 0x44, 0x69, 0xd5, 0x3a, 0xd5, 0xcd, 0x66, 0xef,
	0x1d, 0x29, 0x33, 0x0e, 0xd2, 0x94, 0x05, 0xd2, 0x07, 0x5c, 0xec, 0xc0, 0x22, 0xee, 0x58, 0x8e,
	0x76, 0x69, 0x3f, 0x80, 0xe5, 0xc4, 0x54, 0x68, 0x8b, 0x30, 0xb1, 0x65, 0x05, 0xea, 0x23, 0xc5,
	0xf0, 0x31, 0xb7, 0x8f, 0x75, 0x76, 0x2a, 0xf7, 0x04, 0xf1, 0x1f, 0x01, 0x2e, 0x3d, 0xc2, 0x64,
	0xd7, 0x37, 0x86, 0xa7, 0x71, 0x17, 0x82, 0xda, 0x10, 0x8f, 0xbd, 0x56, 0xa5, 0x53, 0xdd, 0x6c,
	0xc8, 0xb4, 0x8d, 0x3a, 0xd0, 0x74, 0x14, 0x57, 0x31, 0x0c, 0x6c, 0xe8, 0x9e, 0x49, 0x1d, 0x56,
	0x97, 0xe3, 0x43, 0xe8, 0x28, 0x65, 0xfb, 0xbd, 0x7c, 0xdb, 0xa7, 0x21, 0xcd, 0xc6, 0x7e, 0x19,
	0x56, 0x92, 0xba, 0x3c, 0xc7, 0xb6, 0x3c, 0x8c, 0x76, 0xa0, 0xae, 0x13, 0x6c, 0x7a, 0x2d, 0x81,
	0xe2, 0xbc, 0x9e, 0x83, 0x33, 0x12, 0x7c, 0x4c, 0xb0, 0x29, 0x33, 0x11, 0xf1, 0x2f, 0x01, 0x96,
	0x13, 0x13, 0x19, 0x88, 0x10, 0xd4, 0xa8, 0x1b, 0x02, 0x40, 0x4b, 0x32, 0x6d, 0x07, 0x63, 0x98,
	0x28, 0x03, 0xea, 0xb9, 0x86, 0x4c, 0xdb, 0x01, 0x72, 0xec, 0xba, 0xb6, 0xdb, 0xaa, 0x31, 0xe4,
	0xb4, 0x83, 0x9e, 0xc4, 0x1c, 0x59, 0xa7, 0x00, 0x7b, 0x65, 0x00, 0xce, 0xc6, 0x85, 0xbf, 0x09,
	0x70, 0x61, 0x92, 0xab, 0xdc, 0x7f, 0xa1, 0x7d, 0x42, 0x86, 0x7d, 0x95, 0x98, 0x7d, 0x1f, 0xc5,
	0x2c, 0xa9, 0x52, 0x4b, 0xee, 0x9c, 0x78, 0x1c, 0x98, 0x8a, 0xd9, 0x18, 0xf3, 0x43, 0x05, 0xd0,
	0x3e, 0x36, 0x30, 0xc1, 0xaf, 0xc6, 0x1e, 0x59, 0xb1, 0x7c, 0x17, 0x16, 0x6c, 0xc6, 0x11, 0x34,
	0x9a, 0xcd, 0x9e, 0x78, 0x32, 0x9b, 0xc8, 0xa1, 0x08, 0x3a, 0x4c, 0xc5, 0xfc, 0x6e, 0x8e, 0xa7,
	0xd2, 0xf8, 0x67, 0xe3, 0xab, 0x97, 0x70, 0xe1, 0x50, 0x19, 0x9d, 0xca, 0x51, 0x77, 0x61, 0xde,
	0x0b, 0x96, 0x33, 0xe6, 0x68, 0xf6, 0xae, 0x16, 0x78, 0x80, 0x1e, 0x29, 0xbe, 0x5c, 0xfc, 0xae,
	0x02, 0x97, 0x9e, 0xfa, 0x7d, 0x43, 0xf7, 0x5e, 0x1c, 0x8c, 0xb0, 0x45, 0x42, 0x7d, 0x57, 0xa1,
	0xe9, 0xf8, 0x7d, 0xcf, 0xef, 0xc7, 0x15, 0x02, 0x1b, 0xa2, 0x1a, 0x57, 0xa0, 0x4e, 0x6c, 0x47,
	0x57, 0x43, 0xf8, 0xb4, 0x13, 0xa5, 0x67, 0x35, 0x96, 0x9e, 0x5b, 0x70, 0x31, 0xf8, 0x7f, 0xac,
	0xda, 0x16, 0xc1, 0x16, 0x39, 0x26, 0x63, 0x07, 0xf3, 0x63, 0x77, 0x3e, 0x98, 0xd8, 0x63, 0xe3,
	0x47, 0x63, 0x07, 0x27, 0x98, 0xac, 0x5e, 0xc8, 0x64, 0x19, 0xa0, 0x67, 0x13, 0x8d, 0xbf, 0x85,
	0xb0, 0xb8, 0xee, 0xea, 0x96, 0xa6, 0x5b, 0x83, 0xd0, 0x45, 0x08, 0x6a, 0x31, 0xdf, 0xd0, 0x76,
	0x26, 0xfd, 0x3c, 0x4b, 0x1d, 0xc5, 0xfb, 0x39, 0x36, 0x65, 0xa9, 0xc9, 0x33, 0x0a, 0x6d, 0x40,
	0xc3, 0x76, 0xb0, 0xab, 0x04, 0x59, 0xcc, 0xdd, 0x39, 0x19, 0x78, 0x35, 0x93, 0x7f, 0x15, 0x60,
	0x75, 0x0a, 0x4b, 0x01, 0xfd, 0x7c, 0x1c, 0xb3, 0x8f, 0x65, 0xdf, 0x4e, 0x39, 0xfb, 0x66, 0xc9,
	0x37, 0x7f, 0x70, 0xf2, 0xc4, 0xaa, 0x8b, 0xc9, 0x99, 0xd9, 0xe6, 0x74, 0x2c, 0x1a, 0xd7, 0x35,
	0x1b, 0xab, 0xbe, 0x15, 0xe0, 0x62, 0x4c, 0x13, 0x0f, 0xca, 0xfb, 0x51, 0x50, 0x8a, 0x2a, 0x56,
	0x4a, 0x4e, 0xda, 0x8f, 0xe0, 0x51, 0xf9, 0xf6, 0x5d, 0x68, 0xec, 0x9f, 0x09, 0xd6, 0xd7, 0xb0,
	0x7e, 0xe4, 0x2a, 0x96, 0xa7, 0xa8, 0x41, 0xee, 0x29, 0x06, 0x27, 0x5a, 0x9e, 0x8b, 0xe8, 0x3a,
	0x2c, 0x47, 0x89, 0x19, 0x9c, 0x72, 0xbe, 0x69, 0x72, 0x10, 0xdd, 0x87, 0x05, 0x97, 0xf9, 0x8e,
	0x2a, 0x28, 0xc1, 0x61, 0xe1, 0x7a, 0xf1, 0xa7, 0x0a, 0x5c, 0x39, 0xf8, 0x12, 0xab, 0x3e, 0x67,
	0xe7, 0x18, 0x98, 0x30, 0xf4, 0x1b, 0x30, 0x09, 0x74, 0x3a, 0xf2, 0x32, 0x40, 0x04, 0x26, 0xa4,
	0xd0, 0x3c, 0x3f, 0x16, 0x58, 0x2a, 0xc7, 0x76, 0x41, 0xc7, 0xa9, 0xdc, 0xd9, 0xcb, 0xd9, 0xb1,
	0x18, 0xfa, 0x6c, 0x32, 0xe9, 0x77, 0x01, 0xd6, 0x64, 0x3c, 0x08, 0x6e, 0xcf, 0xee, 0x43, 0x95,
	0xd8, 0xee, 0x91, 0x6e, 0x62, 0x37, 0x76, 0x50, 0x94, 0x60, 0x90, 0x71, 0x35, 0x77, 0x17, 0x1d,
	0xa1, 0xa1, 0x5a, 0x83, 0x45, 0x36, 0xad, 0x6b, 0x7c, 0xe7, 0x05, 0xda, 0x7f, 0xac, 0x45, 0xa4,
	0x58, 0x8d, 0x91, 0xe2, 0x1a, 0x2c, 0x6a, 0x3e, 0x3e, 0x0e, 0xcc, 0xe5, 0x44, 0xb5, 0xa0, 0xf9,
	0x38, 0x50, 0x88, 0x2e, 0xc3, 0xbc, 0x83, 0x5d, 0xdd, 0xd6, 0x5a, 0x75, 0x3a, 0xc1, 0x7b, 0xa8,
	0x0d, 0x8b, 0xaa, 0x62, 0x18, 0x7d, 0x45, 0x1d, 0xb6, 0xe6, 0xe9, 0x4c, 0xd4, 0x8f, 0x38, 0x68,
	0x61, 0xc2, 0x41, 0xe2, 0x10, 0xd6, 0x9f, 0x59, 0xee, 0x7f, 0x63, 0x8f, 0xf8, 0xb3, 0x00, 0x1b,
	0x09, 0xdf, 0xc9, 0xd8, 0xd4, 0x2d, 0xed, 0x7f, 0xe4, 0xbe, 0xd0, 0x45, 0xf3, 0x31, 0x17, 0x59,
	0x70, 0x65, 0xca, 0x45, 0x33, 0x85, 0x2d, 0xf6, 0xe9, 0x0b, 0x80, 0x2a, 0x9a, 0xbe, 0xc9, 0x9c,
	0x51, 0x0b, 0xcf, 0xef, 0x6a, 0x94, 0xdf, 0xe2, 0x2d, 0x58, 0x9d, 0xd2, 0x91, 0x5f, 0xa7, 0xc4,
	0x5f, 0x04, 0xb8, 0xc6, 0x8f, 0xda, 0x44, 0x22, 0x83, 0x2a, 0xce, 0x0e, 0xf0, 0x93, 0x04, 0x8d,
	0x54, 0x0b, 0x2f, 0x93, 0x09, 0x1a, 0x99, 0xe0, 0xc9, 0xe4, 0x12, 0xf1, 0x1b, 0x01, 0x3a, 0x27,
	0x09, 0x94, 0xa4, 0xd9, 0x74, 0x91, 0xdb, 0x0a, 0x49, 0x82, 0x7d, 0x12, 0x58, 0x91, 0xd8, 0xc7,
	0x08, 0x29, 0xfc, 0x18, 0x21, 0x3d, 0xb4, 0xc6, 0x9c, 0x3a, 0xc4, 0xaf, 0x00, 0xb1, 0x22, 0xce,
	0x13, 0xe8, 0x55, 0x3d, 0x76, 0x19, 0xe6, 0x4d, 0x4c, 0x5e, 0xd8, 0x1a, 0x8f, 0x2a, 0xef, 0x45,
	0xf1, 0xab, 0xc5, 0xe2, 0x77, 0x13, 0x2e, 0x25, 0x74, 0xe7, 0x87, 0xba, 0xf7, 0xe7, 0x12, 0xd4,
	0xf6, 0x15, 0xc7, 0x45, 0x1a, 0x2c, 0x27, 0x3e, 0x8c, 0xa0, 0x5b, 0x85, 0x57, 0x93, 0xe4, 0xe7,
	0x93, 0xf6, 0xf5, 0xe2, 0xaf, 0x23, 0x0c, 0x80, 0x38, 0x87, 0x3e, 0x83, 0xc5, 0xf0, 0x15, 0x85,
	0xde, 0x2c, 0xf7, 0xd5, 0xa1, 0x7d, 0xa3, 0xe4, 0x73, 0x4c, 0x9c, 0x43, 0x3a, 0x2c, 0xc5, 0xdf,
	0xd2, 0x68, 0xab, 0xfc, 0xe3, 0xbe, 0x7d, 0xab, 0xd4, 0xda, 0x48, 0xd5, 0x13, 0x68, 0x44, 0x4f,
	0x0f, 0x94, 0x07, 0x71, 0xfa, 0x71, 0xd2, 0xbe, 0x9c, 0x4a, 0x99, 0x03, 0xd3, 0x21, 0x63, 0x71,
	0x0e, 0xc9, 0xd0, 0x8c, 0xbd, 0x9a, 0xd0, 0xcd, 0xd2, 0x2f, 0xab, 0x82, 0x3d, 0x5f, 0xc2, 0x6b,
	0x39, 0x15, 0x13, 0xdd, 0x39, 0x53, 0x85, 0x2d, 0xd0, 0x75, 0x04, 0x4b, 0xf1, 0x87, 0x46, 0xae,
	0xeb, 0x33, 0x5e, 0x23, 0x05, 0xbb, 0x1a, 0x61, 0x56, 0xf2, 0xab, 0xf0, 0x09, 0x59, 0x99, 0x7c,
	0x10, 0xb4, 0xdf, 0x3a, 0xcd, 0xed, 0x5a, 0x9c, 0x43, 0x9f, 0x43, 0x23, 0xba, 0xfb, 0xa1, 0x1b,
	0x25, 0xef, 0xaf, 0xed, 0xcd, 0xb2, 0xd7, 0x48, 0xaa, 0x01, 0xa5, 0xef, 0x12, 0xe8, 0xed, 0x9c,
	0x1d, 0x72, 0xaf, 0x1d, 0x05, 0x1e, 0xd3, 0x60, 0x25, 0xab, 0xbe, 0xa3, 0xbc, 0x4b, 0x5a, 0xc1,
	0x65, 0xa0, 0x40, 0xcb, 0x73, 0x58, 0xcd, 0xac, 0xeb, 0xe8, 0x76, 0x19, 0x53, 0xa6, 0xca, 0x69,
	0x71, 0x06, 0xe7, 0x94, 0xe2, 0xdc, 0x0c, 0x2e, 0x2e, 0xdd, 0xc5, 0xb9, 0x96, 0x28, 0x91, 0xa8,
	0x80, 0x11, 0x52, 0xc5, 0x3a, 0x37, 0xd7, 0x32, 0xab, 0xae, 0x38, 0x87, 0x08, 0x6c, 0x14, 0x95,
	0x58, 0xb4, 0x53, 0x7c, 0x40, 0x8b, 0xea, 0x72, 0x61, 0xdc, 0x9a, 0xb1, 0xca, 0x90, 0xcb, 0x32,
	0xe9, 0xca, 0xd5, 0xde, 0x2a, 0xb3, 0x34, 0xb4, 0x6e, 0x57, 0x07, 0xd0, 0x6d, 0x26, 0x31, 0xea,
	0xee, 0x42, 0x50, 0x61, 0x9e, 0x06, 0x92, 0xde, 0xa7, 0xdd, 0x81, 0x4e, 0x5e, 0xf8, 0xfd, 0xa0,
	0x48, 0xd0, 0x5f, 0x02, 0xd8, 0x1f, 0x67, 0x38, 0x48, 0xfd, 0x50, 0xf0, 0x80, 0x37, 0x7f, 0xac,
	0xac, 0x07, 0xf2, 0xd2, 0x9e, 0xa1, 0x63, 0x8b, 0x48, 0x0f, 0x7d, 0x62, 0x0f, 0xb0, 0x25, 0x3d,
	0x72, 0x1d, 0x55, 0x1a, 0x75, 0xfb, 0xf3, 0x54, 0xee, 0xf6, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd7, 0xe4, 0x4b, 0x04, 0x6e, 0x18, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DaprClient is the client API for Dapr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DaprClient interface {
	// Invokes a method on a remote Dapr app.
	InvokeService(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*v1.InvokeResponse, error)
	// Gets the state for a specific key.
	GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error)
	// Gets a bulk of state items for a list of keys
	GetBulkState(ctx context.Context, in *GetBulkStateRequest, opts ...grpc.CallOption) (*GetBulkStateResponse, error)
	// Saves the state for a specific key.
	SaveState(ctx context.Context, in *SaveStateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Deletes the state for a specific key.
	DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Executes transactions for a specified store
	ExecuteStateTransaction(ctx context.Context, in *ExecuteStateTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Publishes events to the specific topic.
	PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Invokes binding data to specific output bindings
	InvokeBinding(ctx context.Context, in *InvokeBindingRequest, opts ...grpc.CallOption) (*InvokeBindingResponse, error)
	// Gets secrets from secret stores.
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	// Register an actor timer.
	RegisterActorTimer(ctx context.Context, in *RegisterActorTimerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Unregister an actor timer.
	UnregisterActorTimer(ctx context.Context, in *UnregisterActorTimerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Register an actor reminder.
	RegisterActorReminder(ctx context.Context, in *RegisterActorReminderRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Unregister an actor reminder.
	UnregisterActorReminder(ctx context.Context, in *UnregisterActorReminderRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Gets the state for a specific actor.
	GetActorState(ctx context.Context, in *GetActorStateRequest, opts ...grpc.CallOption) (*GetActorStateResponse, error)
	// Executes state transactions for a specified actor
	ExecuteActorStateTransaction(ctx context.Context, in *ExecuteActorStateTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// InvokeActor calls a method on an actor.
	InvokeActor(ctx context.Context, in *InvokeActorRequest, opts ...grpc.CallOption) (*InvokeActorResponse, error)
}

type daprClient struct {
	cc *grpc.ClientConn
}

func NewDaprClient(cc *grpc.ClientConn) DaprClient {
	return &daprClient{cc}
}

func (c *daprClient) InvokeService(ctx context.Context, in *InvokeServiceRequest, opts ...grpc.CallOption) (*v1.InvokeResponse, error) {
	out := new(v1.InvokeResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/InvokeService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) GetState(ctx context.Context, in *GetStateRequest, opts ...grpc.CallOption) (*GetStateResponse, error) {
	out := new(GetStateResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/GetState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) GetBulkState(ctx context.Context, in *GetBulkStateRequest, opts ...grpc.CallOption) (*GetBulkStateResponse, error) {
	out := new(GetBulkStateResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/GetBulkState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) SaveState(ctx context.Context, in *SaveStateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/SaveState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) DeleteState(ctx context.Context, in *DeleteStateRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/DeleteState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) ExecuteStateTransaction(ctx context.Context, in *ExecuteStateTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/ExecuteStateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) PublishEvent(ctx context.Context, in *PublishEventRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/PublishEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) InvokeBinding(ctx context.Context, in *InvokeBindingRequest, opts ...grpc.CallOption) (*InvokeBindingResponse, error) {
	out := new(InvokeBindingResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/InvokeBinding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) RegisterActorTimer(ctx context.Context, in *RegisterActorTimerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/RegisterActorTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) UnregisterActorTimer(ctx context.Context, in *UnregisterActorTimerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/UnregisterActorTimer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) RegisterActorReminder(ctx context.Context, in *RegisterActorReminderRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/RegisterActorReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) UnregisterActorReminder(ctx context.Context, in *UnregisterActorReminderRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/UnregisterActorReminder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) GetActorState(ctx context.Context, in *GetActorStateRequest, opts ...grpc.CallOption) (*GetActorStateResponse, error) {
	out := new(GetActorStateResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/GetActorState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) ExecuteActorStateTransaction(ctx context.Context, in *ExecuteActorStateTransactionRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/ExecuteActorStateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daprClient) InvokeActor(ctx context.Context, in *InvokeActorRequest, opts ...grpc.CallOption) (*InvokeActorResponse, error) {
	out := new(InvokeActorResponse)
	err := c.cc.Invoke(ctx, "/dapr.proto.runtime.v1.Dapr/InvokeActor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DaprServer is the server API for Dapr service.
type DaprServer interface {
	// Invokes a method on a remote Dapr app.
	InvokeService(context.Context, *InvokeServiceRequest) (*v1.InvokeResponse, error)
	// Gets the state for a specific key.
	GetState(context.Context, *GetStateRequest) (*GetStateResponse, error)
	// Gets a bulk of state items for a list of keys
	GetBulkState(context.Context, *GetBulkStateRequest) (*GetBulkStateResponse, error)
	// Saves the state for a specific key.
	SaveState(context.Context, *SaveStateRequest) (*empty.Empty, error)
	// Deletes the state for a specific key.
	DeleteState(context.Context, *DeleteStateRequest) (*empty.Empty, error)
	// Executes transactions for a specified store
	ExecuteStateTransaction(context.Context, *ExecuteStateTransactionRequest) (*empty.Empty, error)
	// Publishes events to the specific topic.
	PublishEvent(context.Context, *PublishEventRequest) (*empty.Empty, error)
	// Invokes binding data to specific output bindings
	InvokeBinding(context.Context, *InvokeBindingRequest) (*InvokeBindingResponse, error)
	// Gets secrets from secret stores.
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	// Register an actor timer.
	RegisterActorTimer(context.Context, *RegisterActorTimerRequest) (*empty.Empty, error)
	// Unregister an actor timer.
	UnregisterActorTimer(context.Context, *UnregisterActorTimerRequest) (*empty.Empty, error)
	// Register an actor reminder.
	RegisterActorReminder(context.Context, *RegisterActorReminderRequest) (*empty.Empty, error)
	// Unregister an actor reminder.
	UnregisterActorReminder(context.Context, *UnregisterActorReminderRequest) (*empty.Empty, error)
	// Gets the state for a specific actor.
	GetActorState(context.Context, *GetActorStateRequest) (*GetActorStateResponse, error)
	// Executes state transactions for a specified actor
	ExecuteActorStateTransaction(context.Context, *ExecuteActorStateTransactionRequest) (*empty.Empty, error)
	// InvokeActor calls a method on an actor.
	InvokeActor(context.Context, *InvokeActorRequest) (*InvokeActorResponse, error)
}

// UnimplementedDaprServer can be embedded to have forward compatible implementations.
type UnimplementedDaprServer struct {
}

func (*UnimplementedDaprServer) InvokeService(ctx context.Context, req *InvokeServiceRequest) (*v1.InvokeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeService not implemented")
}
func (*UnimplementedDaprServer) GetState(ctx context.Context, req *GetStateRequest) (*GetStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (*UnimplementedDaprServer) GetBulkState(ctx context.Context, req *GetBulkStateRequest) (*GetBulkStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBulkState not implemented")
}
func (*UnimplementedDaprServer) SaveState(ctx context.Context, req *SaveStateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveState not implemented")
}
func (*UnimplementedDaprServer) DeleteState(ctx context.Context, req *DeleteStateRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteState not implemented")
}
func (*UnimplementedDaprServer) ExecuteStateTransaction(ctx context.Context, req *ExecuteStateTransactionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteStateTransaction not implemented")
}
func (*UnimplementedDaprServer) PublishEvent(ctx context.Context, req *PublishEventRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishEvent not implemented")
}
func (*UnimplementedDaprServer) InvokeBinding(ctx context.Context, req *InvokeBindingRequest) (*InvokeBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeBinding not implemented")
}
func (*UnimplementedDaprServer) GetSecret(ctx context.Context, req *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (*UnimplementedDaprServer) RegisterActorTimer(ctx context.Context, req *RegisterActorTimerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterActorTimer not implemented")
}
func (*UnimplementedDaprServer) UnregisterActorTimer(ctx context.Context, req *UnregisterActorTimerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterActorTimer not implemented")
}
func (*UnimplementedDaprServer) RegisterActorReminder(ctx context.Context, req *RegisterActorReminderRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterActorReminder not implemented")
}
func (*UnimplementedDaprServer) UnregisterActorReminder(ctx context.Context, req *UnregisterActorReminderRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterActorReminder not implemented")
}
func (*UnimplementedDaprServer) GetActorState(ctx context.Context, req *GetActorStateRequest) (*GetActorStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActorState not implemented")
}
func (*UnimplementedDaprServer) ExecuteActorStateTransaction(ctx context.Context, req *ExecuteActorStateTransactionRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteActorStateTransaction not implemented")
}
func (*UnimplementedDaprServer) InvokeActor(ctx context.Context, req *InvokeActorRequest) (*InvokeActorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InvokeActor not implemented")
}

func RegisterDaprServer(s *grpc.Server, srv DaprServer) {
	s.RegisterService(&_Dapr_serviceDesc, srv)
}

func _Dapr_InvokeService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).InvokeService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/InvokeService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).InvokeService(ctx, req.(*InvokeServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/GetState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).GetState(ctx, req.(*GetStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_GetBulkState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBulkStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).GetBulkState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/GetBulkState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).GetBulkState(ctx, req.(*GetBulkStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_SaveState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).SaveState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/SaveState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).SaveState(ctx, req.(*SaveStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_DeleteState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).DeleteState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/DeleteState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).DeleteState(ctx, req.(*DeleteStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_ExecuteStateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteStateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).ExecuteStateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/ExecuteStateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).ExecuteStateTransaction(ctx, req.(*ExecuteStateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_PublishEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).PublishEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/PublishEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).PublishEvent(ctx, req.(*PublishEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_InvokeBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).InvokeBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/InvokeBinding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).InvokeBinding(ctx, req.(*InvokeBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_RegisterActorTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterActorTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).RegisterActorTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/RegisterActorTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).RegisterActorTimer(ctx, req.(*RegisterActorTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_UnregisterActorTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterActorTimerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).UnregisterActorTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/UnregisterActorTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).UnregisterActorTimer(ctx, req.(*UnregisterActorTimerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_RegisterActorReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterActorReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).RegisterActorReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/RegisterActorReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).RegisterActorReminder(ctx, req.(*RegisterActorReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_UnregisterActorReminder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterActorReminderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).UnregisterActorReminder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/UnregisterActorReminder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).UnregisterActorReminder(ctx, req.(*UnregisterActorReminderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_GetActorState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActorStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).GetActorState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/GetActorState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).GetActorState(ctx, req.(*GetActorStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_ExecuteActorStateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteActorStateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).ExecuteActorStateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/ExecuteActorStateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).ExecuteActorStateTransaction(ctx, req.(*ExecuteActorStateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dapr_InvokeActor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeActorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaprServer).InvokeActor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dapr.proto.runtime.v1.Dapr/InvokeActor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaprServer).InvokeActor(ctx, req.(*InvokeActorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dapr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dapr.proto.runtime.v1.Dapr",
	HandlerType: (*DaprServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InvokeService",
			Handler:    _Dapr_InvokeService_Handler,
		},
		{
			MethodName: "GetState",
			Handler:    _Dapr_GetState_Handler,
		},
		{
			MethodName: "GetBulkState",
			Handler:    _Dapr_GetBulkState_Handler,
		},
		{
			MethodName: "SaveState",
			Handler:    _Dapr_SaveState_Handler,
		},
		{
			MethodName: "DeleteState",
			Handler:    _Dapr_DeleteState_Handler,
		},
		{
			MethodName: "ExecuteStateTransaction",
			Handler:    _Dapr_ExecuteStateTransaction_Handler,
		},
		{
			MethodName: "PublishEvent",
			Handler:    _Dapr_PublishEvent_Handler,
		},
		{
			MethodName: "InvokeBinding",
			Handler:    _Dapr_InvokeBinding_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _Dapr_GetSecret_Handler,
		},
		{
			MethodName: "RegisterActorTimer",
			Handler:    _Dapr_RegisterActorTimer_Handler,
		},
		{
			MethodName: "UnregisterActorTimer",
			Handler:    _Dapr_UnregisterActorTimer_Handler,
		},
		{
			MethodName: "RegisterActorReminder",
			Handler:    _Dapr_RegisterActorReminder_Handler,
		},
		{
			MethodName: "UnregisterActorReminder",
			Handler:    _Dapr_UnregisterActorReminder_Handler,
		},
		{
			MethodName: "GetActorState",
			Handler:    _Dapr_GetActorState_Handler,
		},
		{
			MethodName: "ExecuteActorStateTransaction",
			Handler:    _Dapr_ExecuteActorStateTransaction_Handler,
		},
		{
			MethodName: "InvokeActor",
			Handler:    _Dapr_InvokeActor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dapr/proto/runtime/v1/dapr.proto",
}
