# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.
# ------------------------------------------------------------

FROM golang:1.17-nanoserver

WORKDIR /app
COPY . .
RUN go get -d -v
RUN go build -o app.exe .

CMD ["app.exe"]
