# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

FROM golang:1.15-nanoserver-1809

WORKDIR /app
COPY . .

CMD ["app.exe"]
