apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.dapr.io
  namespace: {{ .Release.Namespace }}
spec:
  group: dapr.io
  version: v1alpha1
  names:
    kind: Component
    plural: components
    singular: component
    categories:
    - all
    - dapr
  scope: Namespaced