apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.actions.io
  namespace: {{ .Release.Namespace }}
spec:
  group: actions.io
  version: v1alpha1
  names:
    kind: Component
    plural: components
    singular: component
    categories:
    - all
    - actions
  scope: Namespaced