# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
# ------------------------------------------------------------

FROM golang:1.15-windowsservercore-1809

WORKDIR /app
COPY . .
RUN go build -o app.exe .

CMD ["app.exe"]
