kind: Service
apiVersion: v1
metadata:
  name: dapr-api
spec:
  selector:
    app: dapr-operator
  ports:
  - protocol: TCP
    port: {{ .Values.ports.port }} 
    targetPort: {{ .Values.ports.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: dapr-webhook
spec:
  ports:
  - port: 443
    targetPort: 19443
    protocol: TCP
  selector:
    app: dapr-operator