# This helm hook patches the subscription CRD to include the correct conversion webhook namespace and caBundle.
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-crd
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: patch-crd
    spec:
      serviceAccountName: dapr-operator # Needed for permissions to run the CRD patch below.
      restartPolicy: Never
      containers:
      - name: sa
        {{ if eq .Values.global.daprControlPlaneOs "windows" }}
        image: codefresh/kubectl:windows-20H2
        {{ else }}
        image: codefresh/kubectl:1.18.2
        {{ end }}
        imagePullPolicy: IfNotPresent
        # The `kubectl patch` below updates the namespace and caBundle for the subscription CRD conversion webhook.
        command:
        - "/bin/sh"
        - "-c"
        - |
          export caBundle=`kubectl get secret -n {{ .Release.Namespace }} dapr-webhook-ca -o jsonpath="{.data.caBundle}"`
          kubectl patch crd "subscriptions.dapr.io" --type='json' -p "[{'op': 'add', 'path': '/spec/conversion/webhook/clientConfig/service/namespace', 'value':'{{ .Release.Namespace }}'},{'op': 'add', 'path': '/spec/conversion/webhook/clientConfig/caBundle', 'value':'${caBundle}'}]"