dependencies:
- name: dapr_rbac
  version: "0.2.0"
  repository: "file://dapr_rbac"
- name: dapr_operator
  version: "0.2.1"
  repository: "file://dapr_operator"
- name: dapr_placement
  version: "0.2.1"
  repository: "file://dapr_placement"
- name: dapr_sidecar_injector
  version: "0.2.1"
  repository: "file://dapr_sidecar_injector"
- name: dapr_sentry
  version: "0.2.1"
  repository: "file://dapr_sentry"
