kind: Service
apiVersion: v1
metadata:
  name: actions-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: actions-controller
  ports:
  - protocol: TCP
    port: {{ .Values.ports.port }} 
    targetPort: {{ .Values.ports.targetPort }}  