kind: Service
apiVersion: v1
metadata:
  name: dapr-placement
spec:
  selector:
    app: dapr-placement
  ports:
  - protocol: TCP
    port: {{ .Values.ports.port }} 
    targetPort: {{ .Values.ports.targetPort }}
