kind: Service
apiVersion: v1
metadata:
  name: actions-placement
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: actions-placement
  ports:
  - protocol: TCP
    port: {{ .Values.ports.port }} 
    targetPort: {{ .Values.ports.targetPort }}
