apiVersion: apps/v1
kind: Deployment
metadata:
  name: divideapp
  labels:
    app: divide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: divide
  template:
    metadata:
      labels:
        app: divide
      annotations:
        actions.io/enabled: "true"
        actions.io/id: "divideapp"
        actions.io/port: "4000"
    spec:
      containers:
      - name: divide
        image: actionscore.azurecr.io/samples/node-divider
        ports:
        - containerPort: 4000
        imagePullPolicy: Always
