apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplyapp
  labels:
    app: multiply
  annotations:
    actions.io/enabled: "true"
    actions.io/id: "multiplyapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiply
  template:
    metadata:
      labels:
        app: multiply
    spec:
      containers:
      - name: multiply
        image: actionscore.azurecr.io/samples/python-multiplier
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
