replicaCount: 1
logLevel: info

image:
  repository: actionscore.azurecr.io/actions
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

ports:
  protocol: TCP
  port: 80
  targetPort: 50005