replicaCount: 1
logLevel: info

# Specify full docker image name including registry url to use a custom sentry service image
# Otherwise, helm chart will use {{ .Values.global.registry }}/dapr:{{ .Values.global.tag }}
image:
  name: ""

nameOverride: ""
fullnameOverride: ""

ports:
  protocol: TCP
  port: 80
  targetPort: 50001

tls:
  issuer:
    certPEM: ""
    keyPEM: ""
  root:
    certPEM: ""
  trustDomain: cluster.local

livenessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 5
readinessProbe:
  initialDelaySeconds: 3
  periodSeconds: 3
  failureThreshold: 5

debug:
  enabled: false
  port: 40000
  initialDelaySeconds: 30000

runAsNonRoot: true
resources: {}
