replicaCount: 1
logLevel: info

image:
  name: dapr

nameOverride: ""
fullnameOverride: ""

ports:
  protocol: TCP
  port: 80
  targetPort: 50001

tls:
  issuer:
    certPEM: ""
    keyPEM: ""
  root:
    certPEM: ""
  trustDomain: cluster.local