# escape=`
ARG WINDOWS_VERSION=1809

FROM daprio/windows-java-base:$WINDOWS_VERSION as build

RUN mkdir "c:\build"
WORKDIR "c:\build"

COPY pom.xml .
RUN mvn dependency:go-offline

ADD src/ "c:\build\src\"
RUN mvn package

FROM daprio/windows-java-base:$WINDOWS_VERSION
COPY --from=build "c:\build\target\app.jar" app.jar

EXPOSE 3000
ENTRYPOINT java -jar app.jar --server.port=3000