# escape=`
ARG JAVA_VERSION=11.0.6

FROM mcr.microsoft.com/dotnet/framework/runtime:4.8-windowsservercore-ltsc2019 as build

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ENV chocolateyUseWindowsCompression=false
RUN iex (wget 'https://chocolatey.org/install.ps1' -UseBasicParsing)

RUN choco feature enable -n=allowGlobalConfirmation
RUN choco feature disable -n=showDownloadProgress
RUN choco config set cachelocation C:\chococache

RUN choco install ojdkbuild11 maven --limit-output --timeout 3600; Remove-Item C:\chococache  -Recurse -Force

RUN mkdir "c:\build"
WORKDIR "c:\build"

RUN refreshenv
COPY pom.xml .
RUN mvn dependency:go-offline

ADD src/ "c:\build\src\"
RUN mvn package

FROM openjdk:${JAVA_VERSION}-windowsservercore-1809
COPY --from=build "c:\build\target\app.jar" app.jar

EXPOSE 3000
ENTRYPOINT java -jar app.jar --server.port=3000