apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonapp
  labels:
    app: python
  annotations:
    actions.io/enabled: "true"
    actions.io/id: "pythonapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: yaron2/pythonapp
