apiVersion: actions.io/v1alpha1
kind: EventSource
metadata:
  name: statestore
spec:
  type: actions.state.redis
  connectionInfo:
    redisHost: "YOUR_REDIS_HOST_HERE"
    redisPassword: "YOUR_REDIS_KEY_HERE"