apiVersion: v1
kind: ServiceAccount
metadata:
  name: dapr-operator
  labels:
    {{- range $key, $value := .Values.global.k8sLabels }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-reader
  labels:
    {{- range $key, $value := .Values.global.k8sLabels }}
    {{ $key }}: {{ tpl $value $ }}
    {{- end }}