name: Daily Alpha Release

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6am
  workflow_dispatch:

jobs:
  new-alpha-release:
    name: New Alpha Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate alpha version
        id: version
        run: |
          # Fetch latest tag from git
          latest=$(git ls-remote --tags origin | \
            grep -o 'refs/tags/v[0-9]*\.[0-9]*\.[0-9]*$' | \
            sed 's/refs\/tags\/v//' | sort -V | tail -n1)
          echo "Latest tag: ${latest}"
          alpha_version="0.0.0-alpha"
          echo "rel_version=${alpha_version}" >> "$GITHUB_OUTPUT"          
      - name: Create Release
        uses: ./.github/workflows/create-release.yml
        with:
          rel_version: ${{ steps.version.outputs.rel_version }}