# ------------------------------------------------------------
# Copyright (c) Microsoft Corporation and Dapr Contributors.
# Licensed under the MIT License.
# ------------------------------------------------------------

name: Validate build for E2E test apps

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - release-*

jobs:
  pre_job:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          cancel_others: true
          paths_ignore: '["**.md", ".codecov.yaml", ".github/**/**.yml"]'
  build:
    name: Build on ${{ matrix.target_os }}_${{ matrix.target_arch }}
    needs: pre_job
    runs-on: ${{ matrix.os }}
    env:
      GOVER: 1.16
      GOOS: ${{ matrix.target_os }}
      GOARCH: ${{ matrix.target_arch }}
      GOPROXY: https://proxy.golang.org
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        target_arch: [arm, arm64, amd64]
        include:
          - os: ubuntu-latest
            target_os: linux
          - os: windows-latest
            target_os: windows
        exclude:
          - os: windows-latest
            target_arch: arm
          - os: windows-latest
            target_arch: arm64
    steps:
      - name: Set up Go ${{ env.GOVER }}
        uses: actions/setup-go@v2
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
        with:
          go-version: ${{ env.GOVER }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
      - name: Build all E2E test apps
        env:
          TARGET_OS: ${{ matrix.target_os }}
          TARGET_ARCH: ${{ matrix.target_arch }}
          DAPR_TEST_REGISTRY: localhost:5000
          DAPR_TEST_TAG: dev
        run: make build-e2e-app-all
        if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
