name: dapr-wk-test

on:
  push:

jobs:
  wktest:
    name: bot-processor
    runs-on: ubuntu-latest
    steps:
      - name: Setup test output
        run: |
          export TEST_OUTPUT_FILE_PREFIX=$GITHUB_WORKSPACE/test_report
          echo "TEST_OUTPUT_FILE_PREFIX=$TEST_OUTPUT_FILE_PREFIX" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v3 # required to make the script available for next step
      - name: Summary writer
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/dapr_tests_summary.js')
            await script({core, glob})
