---
# Source: actions-operator/charts/actions_crd/templates/components.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: components.actions.io
  namespace: default
spec:
  group: actions.io
  version: v1alpha1
  names:
    kind: Component
    plural: components
    singular: components
    categories:
    - all
    - actions
  scope: Namespaced