---
# Source: actions-operator/charts/actions_placement/templates/actions_placement_service.yaml
kind: Service
apiVersion: v1
metadata:
  name: actions-placement
  namespace: default
spec:
  selector:
    app: actions-placement
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 50005
