{{- if eq .Values.global.ha.enabled true }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: dapr-sentry-budget
  labels:
    app: dapr-sentry
spec:
{{- if .Values.global.ha.disruption.minimumAvailable }}
  minAvailable: {{ .Values.global.ha.disruption.minimumAvailable }}
{{- end }}
{{- if .Values.global.ha.disruption.maximumUnavailable }}
  maxUnavailable: {{ .Values.global.ha.disruption.maximumUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app: dapr-sentry
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Values.global.tag }}
      app.kubernetes.io/component: sentry
      app.kubernetes.io/part-of: "dapr"
      app.kubernetes.io/managed-by: "helm"
{{- end }}