ARG WINDOWS_VERSION=ltsc2022
FROM ghcr.io/dapr/windows-python-base:$WINDOWS_VERSION
WORKDIR /app
ADD . /app
RUN pip install -r requirements.txt

EXPOSE 3000
ENTRYPOINT ["python"]
CMD ["flask_service.py"]

